### ISSUE TITLE
onNotification does not fire when received on Android

### ISSUE THREAD

**Issue by JonesN3** [zo0r/react-native-push-notification#170] opened 2016-08-23 13:28 UTC
Is this feature not supported on android, or am I doing something wrong?

**Comment by heminm** [comment] 2016-08-25 17:51
What version of the package and RN are you using? Are you trying local or remote notification?

**Comment by JonesN7** [comment] 2016-08-31 18:18
RN 30, local notifications.

**Comment by vikeri** [comment] 2016-09-13 13:29
I have the same issue with local notifications, when I schedule one and it fires `onNotification` is not triggered. But if I click the notification it is.

**Comment by juanpasolano** [comment] 2016-09-13 15:35
Same issue:
RN 0.30, 
react-native-push-notification 2.0.2

**Comment by barroslee** [comment] 2016-09-18 16:57
I got same issue with local notifications and RN 0.33.0. `onNotification()` is not called until I click the notification. I just add `notifyNotification()` in `sendNotification()` for a temporarily solution....

**Comment by npomfret** [comment] 2016-09-18 18:30
So the previous behaviour was for onNotification() to be called immediately after sending a local (or scheduled) notification?

Does this only affect Android?

Has it started happening since RN 0.33?

**Comment by vikeri** [comment] 2016-09-19 05:51
It never worked for me. I added this library around 0.31.0 only doing Android for now though. Looked through the Java code but could not find any callback to JS in the code that runs when the notification is fired.

**Comment by vikeri** [comment] 2016-09-19 05:54
i.e. I'm not sure it ever worked as @npomfret describes

**Comment by npomfret** [comment] 2016-09-19 08:36
Sorry, I was just asking a question.  In order to fix it I need to know what is the desired / expected behaviour for receipt of a local notification?  What does the iOS implementation do?

**Comment by barroslee** [comment] 2016-09-19 09:07
Hi @npomfret , I am not sure what's the real behavior. Just because I click the notification, `onNewIntent()` will be called. then `notifyNotification()` will fire event 'remoteNotificationReceived' to trigger onNotification. So I add it in `sendNotification()`.

In ios when app is foreground, the notification never appear but just trigger onNotification.

I upgrade to RN 0.33 from RN 0.30. Both of them also have this issue.

**Comment by npomfret** [comment] 2016-09-19 09:17
I think, but am not sure, the iOS behaviour is that local notifications just go into the notification center and no events are fired.  When the user clicks on a notification it is then that the _onNotification_ js call happens.  Is the Android behaviour is the same right now?  If so, I would suggest there isn't a bug here.

I don't quite understand how the `remoteNotificationReceived` triggers _onNotification_?  Looking at the docs for iOS and js code it seems that the only events being listened to are register, notification, localNotification and remoteFetch.  Have you any idea how this works?

**Comment by npomfret** [comment] 2016-09-19 10:16
Ok, I think the answer to the question "what should the behaviour be?" is _the same as iOS_, right?

I think the iOS behaviour is this:

1) Send a local notification while app is in the background -> the notification appears in the notification centre but `onNotification` is **not** called.

2) Send a local notification while app is in the foreground -> the notification does not appear in the notification centre but `onNotification` is called.

3) Click on an alert in the notification centre when the app is in background -> `onNotification` is called.

Does that sound correct?

**Comment by mcmatan** [comment] 2016-12-25 20:34
@npomfret Yes, you are correct that is the way is works on IOS, and I really wish it would be the same on android (:

**Comment by avdept** [comment] 2017-05-23 12:33
Any progress on this? Not getting onNotification called while app in foreground on android

**Comment by pawlowskim** [comment] 2017-06-26 10:22
Same issue. "onNotification" is not called on Android when notification arrives (only shows in notification center). After clicking the notification "onNotification" is triggered (but in that case, alert I want to display isn't showing because application can be in inactive state probably, when I added delay it start working).

**Comment by kesha-antonov** [comment] 2017-08-01 12:32
Hello guys! @npomfret 
Did you find time to fix it?

**Comment by pawlowskim** [comment] 2017-08-07 12:51
We do some tests. We make a fork and implement notification to show in notification center only if application is in background. If application is in foreground we dispatch event to JS that arrives in "onNotification" from PushNotification.configure object (works the way it works on iOS). On both events we show alert. Now we can say, that alert triggered from notification in both cases not shows every time. We don't know why yet and I can't guarantee we gonna investigate it. 

You can test this fork https://github.com/MateuszMxxxx/react-native-push-notification but the code might not work correctly in every case (lack of native skill :/ ). We gonna make PR for this fork in the future.

**Comment by nonameolsson** [comment] 2017-09-07 03:42
Hi! I have been struggling with this strange problem for a couple of hours before finding this issue. I'm not sure what the current status on this is? And I'm not sure it's the same problem I have. I will describe my problem, and maybe you could guide me on how to solve it?

The function called `onNotification` has following instructions in the documentation: `// (required) Called when a remote or local notification is opened or received`.
When a notification is showing and I press it this callback is triggered. But if I don’t do anything then it’s never triggered.

As I understand it, this callback should be triggered whenever a notification is triggered, right? And the only thing that should change is `notification.userInteration`?

What I need to do is when a notification is showed I need to dispatch an action to remove stuff from my Redux store. So this is the callback I should be using, right?

Here is a video showing my problem:

**Comment by nazywamsiepawel** [comment] 2017-09-07 11:47
Any progress on this? Is the onNotification not called on purpose?

**Comment by gpopovic** [comment] 2017-10-26 10:29
Any progress?

**Comment by ital0** [comment] 2017-10-31 11:20
btw, there's a [PR](https://github.com/zo0r/react-native-push-notification/pull/574) waiting for aproval. For me now fires onNotification (tested only in foreground).

**Comment by butterfly-thomasdittmar** [comment] 2017-11-14 03:41
My app is sitting in Beta (Google Play Console) for over 2 months now. 

Everything is working fine in iOS. I get remote PN and it wakes up the app, redirects the router to the correct page because `onNotification()` gets called in iOS every time (app closed, app open in background and app in foreground).

Unfortunately `onNotification()` only gets called on Android when the app is in foreground. 

I really hope this issue gets resolved soon. BTW @ital0 the PR you are referring to does not resolve the problem when the app is closed and in the background. I have really tried every solution available in the issue section without success.
```
"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-native-push-notification": "^3.0.1"
```

**Comment by ital0** [comment] 2017-11-14 12:00
@butterfly-thomasdittmar  PR works for me, even when app is closed. Strange that doesn't works for you. 
When app is closed, the notification came a little different that when app is in foreground.

**Comment by ErikMikkelson** [comment] 2017-11-14 12:58
I updated that PR because I noticed that the userInteraction flag was overridden to false.  Also @butterfly-thomasdittmar, @iggyfisk's solution from [122](https://github.com/zo0r/react-native-push-notification/issues/122) worked for me.

I can receive notifications in the foreground and background on iOS and in the foreground and background (cold and warm start) on Android with Android firing the onNotification event.  I'm not sure how much of this is bubble gum and bailing wire

**Comment by nonameolsson** [comment] 2017-12-03 15:08
So, there is a PR fixing this issue? But it doesn't get merged? How so?

**Closed** 2018-07-04 21:14 UTC

**Comment by NikhilP99** [comment] 2019-06-26 06:35
In my case, it is not working even when clicked on the notification. onNotification is bever called.
RN 0.59.4

**Comment by Adr1ann** [comment] 2020-01-09 07:48
Any solution? Still not working...
