### ISSUE TITLE
Duplicate notifications are triggering when app is in background with FCM 

### ISSUE THREAD

**Issue by Sahil5963** [zo0r/react-native-push-notification#1354] opened 2020-04-01 18:33 UTC
I am getting duplicate notification (FCM) when app is in background ,
and only getting single notification when app is in foreground or close, but the problem lies with background state

```xml
<manifest` xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.bizfeed">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" /> <!-- <- Add this line -->
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />

    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" /> <!-- < Only if you're using GCM or localNotificationSchedule() > -->
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <application
      android:name="com.bizfeed.MainApplication"

      android:label="@string/app_name"
      android:icon="@drawable/logos"
      android:roundIcon="@drawable/logos"
      android:allowBackup="false"
        android:usesCleartextTraffic="true"
        tools:ignore="GoogleAppIndexingWarning"
      android:theme="@style/AppTheme">
        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />
        <activity
            android:name="com.bizfeed.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:exported="true"
            android:launchMode="singleInstance"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustUnspecified">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="bizzfeed.page.link"
                    android:scheme="https" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="YOUR NOTIFICATION CHANNEL NAME" />
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION" /> <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white" /> <!-- < Only if you're using GCM or localNotificationSchedule() > -->
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />

                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver> <!-- < Only if you're using GCM or localNotificationSchedule() > -->
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

<!--       Background(Closed) <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" /> &lt;!&ndash; < Only if you're using GCM or localNotificationSchedule() > &ndash;&gt;-->

<!--        CLOSED-->
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
<!--        CLOSED END-->


        <!-- </ Only if you're using GCM or localNotificationSchedule() > -->
        <!-- < Else > -->
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

<!--        Foreground-->
<!--        <service android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService">-->
<!--            <intent-filter>-->
<!--                <action android:name="com.google.firebase.MESSAGING_EVENT" />-->
<!--            </intent-filter>-->
<!--        </service>-->
    </application>

</manifest>
```

**Comment by chenop** [comment] 2020-04-02 08:31
I got the same issue - in my case its seems another mechanism (app is quite old) is pushing notification in native code.

Search your native code (android / ios) for "push" or "notif"

**Comment by davidrenji** [comment] 2020-04-04 23:44
it looks like removing this fix the duplicate notification:


    <receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />

            <category android:name="${applicationId}" />
        </intent-filter>
    </receiver>

**Comment by Dallas62** [comment] 2020-04-09 06:09
Hi @davidrenji 
If it's good for you, can you close this issue ?
Thanks !

**Comment by cpecorari** [comment] 2020-04-10 08:08
> it looks like removing this fix the duplicate notification:
> 
> ```
> <receiver
>     android:name="com.google.android.gms.gcm.GcmReceiver"
>     android:exported="true"
>     android:permission="com.google.android.c2dm.permission.SEND">
>     <intent-filter>
>         <action android:name="com.google.android.c2dm.intent.RECEIVE" />
> 
>         <category android:name="${applicationId}" />
>     </intent-filter>
> </receiver> 
> ```

In my case, doubled again, so 4 identical notifications ;)

But what did the trick for me, following [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/android/client?authuser=1) is to add 
`<service
    android:name=".java.MyFirebaseMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>`

in my Manifest.xml. Hope that could help !
In any case, wondering why we still use C2DM in react-native-push-notification but completely [shut down in 2015 by Google](https://developers.google.com/android/c2dm?hl=fr) in favor of FCM ?

**Comment by Dallas62** [comment] 2020-04-10 08:18
Hi @cpecorari 
You should clear you Manifest.xml, there is duplicate code:
```xml
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
```

This service or the other one might be duplicate as suggested by @davidrenji 
```xml
    <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Your solution with `.java.MyFirebaseMessagingService` do not use the library (I guess).

I will take a look at the link you have provide,
Thanks !

**Comment by cpecorari** [comment] 2020-04-10 09:45
Hey @Dallas62  thanks, you were right, so i changed again the @davidrenji suggestion after more testing, and now using instead of removing :
```xml
 <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
```
instead of specific FCM Java lib that i removed.
So i can now pop my notification when in background from FCM, and action is made when notification is clicked.
But when in foreground, no notification is triggered, and no action either in RNPN ... 
I think i still miss something but don't know what !
Anyway, i now have only 1 notification and can trigger actions on click.

**Comment by Dallas62** [comment] 2020-04-10 10:00
I found this issue:
https://github.com/invertase/react-native-firebase/issues/1642

I think it's the same kind of issue, did you set a channel to your remote notification ?

**Comment by cpecorari** [comment] 2020-04-10 10:31
In the Manifest you mean ? 
```xml
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="MYAPPNAME_SPECIFICSUBJECT"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="MYAPP for specific"/>
```
I did. In backend could not find a way. I will try rn-firebase to see if any difference, and change my backend for official FCM Admin.

**Comment by Dallas62** [comment] 2020-04-10 11:24
I was thinking about the remote server, when you send your notification.
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification
The `channel_id` field.

Take care, rn-firebase removed a part of notification management.

**Comment by cpecorari** [comment] 2020-04-10 13:16
Ho yeah just saw you need Notifee to manage notifications correctly...
Trying to change my backend with channel_id, will update ! Thanks

**Comment by cpecorari** [comment] 2020-04-10 15:33
Finally managed to get it working correctly background and foreground. But can't handle Notification before clicking on it on iOS. Just possible in Android in Foreground. Is that normal behavior ?

I changed my backend for official Google FCM Admin with json credentials. Still can't set channel_id because i set token specifically, and it can't be both.
I think the RNPN documentation should be updated for handling specifically FCM remote notifications don't you think ?

Partly following [this issue](https://github.com/zo0r/react-native-push-notification/issues/796) here are my Manifest and Gradle for remote notif (local working also, though i don't need it) and differences with GitHub doc as far as i can tell : 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.mobileapp">

    <uses-permission android:name="android.permission.INTERNET" />
<!-- < Only if you're using GCM or localNotificationSchedule() > -->
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <!-- < Only if you're using GCM or localNotificationSchedule() > -->

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="notusedbuthereitis"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="whatever"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>
                    <!-- < Only if you're using GCM or localNotificationSchedule() > -->
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <!-- < Only if you're using GCM or localNotificationSchedule() > -->

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service // Needed to add this one linked to RNPN Listener Service
        android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
        android:exported="false" >
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
    </service>

        <!-- < Only if you're using GCM or localNotificationSchedule() > -->
        <!-- <service // had to remove this one
android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service> -->
        <!-- </ Only if you're using GCM or localNotificationSchedule() > -->
    </application>

</manifest>
```
App build.gradle : 
```js
...
android {
  ...
    defaultConfig {
        ...
        multiDexEnabled true // If you start having too much methods Gradle will stop if you don't enable it
    }
}
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services' // Add this one

```

and android build.gradle : 
```js
buildscript {
   ...
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.3.3' // Added this one
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
...
}
```

**Comment by Dallas62** [comment] 2020-05-05 16:16
Hi @chenop I think this is fixed in 3.3.1.

**Comment by marqroldan** [comment] 2020-05-08 11:36
I just wanna add that I got this to work properly (even before 3.3.1) by removing the  `c2dm` related code. And then after upgrading to 3.3.1, it was working for a while and then laterl it's showing duplicate again, then I had to reinstall the app and it's working properly again.

When it was showing duplicate notification, it's something that I sent from the node sdk. But if it was through the `https://fcm.googleapis.com/fcm/send`  endpoint it was only showing one. I could not identify the difference on the payload

There's also a fix here [https://github.com/zo0r/react-native-push-notification/issues/1173#issuecomment-571392983] but i haven't tried that yet since reinstalling fixed it

**Comment by Dallas62** [comment] 2020-05-12 18:02
Any update on the initial issue ?

**Comment by Dallas62** [comment] 2020-05-20 11:22
This issue should not occured with the latest version, you will need to check the installation process in the README.
Many settings in AndroidManifest are not required anymore.

**Closed by Dallas62** 2020-05-20 11:22 UTC

**Comment by kidfrom** [comment] 2020-09-23 08:02
@Dallas62 Confirmed this happens in version `"react-native-push-notification": "^5.1.1"`

android/app/src/AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.push1a2b">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
              android:value="YOUR NOTIFICATION CHANNEL NAME"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                  android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>

      <!-- Change the value to true to enable pop-up for in foreground (remote-only, for local use ignoreInForeground) -->
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
      <!-- Change the value to false if you don't want the creation of the default channel -->
      <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                  android:value="true"/>
      <!-- Change the resource name to your App's accent color - or any other color you want -->
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
          </intent-filter>
      </receiver>

      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

android/app/build.gradle
```
apply plugin: 'com.google.gms.google-services'

dependencies {
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
}
```

android/build.gradle
```
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

App.js
```
const App: () => React$Node = () => {
  React.useEffect(() => {
    const unsubscribe = messaging().onMessage(async (remoteMessage) => {
      console.log(remoteMessage);
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
      PushNotification.localNotification({
        title: remoteMessage.notification.title,
        message: remoteMessage.notification.body,
        
        largeIcon: "",
        largeIconUrl: remoteMessage.notification.android.imageUrl,
      })
    });

    return unsubscribe;
  }, []);
  return <></>;
};
```

**Comment by ahossamdev** [comment] 2023-02-16 10:19
i'm facing this problem till now @Dallas62 did it solved ?

**Comment by Dallas62** [comment] 2023-02-16 10:20
Please read the state of the repository in the Readme,
Regards

**Comment by ahossamdev** [comment] 2023-02-16 10:21
okay , thank you.
