### ISSUE TITLE
Execution failed for task ':react-native-push-notification:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by sidVaidya** [zo0r/react-native-push-notification#1987] opened 2021-05-12 10:41 UTC
# Bug

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.React-native: 0..60.4
2.react-native-push-notification: 7.2.0
...
android/gradlew:
 ext {
        googlePlayServicesVersion = "+"
        firebaseMessagingVersion= "+"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
        googlePlayServicesAuthVersion = "16.0.1"
    }
Error log:

> Task :react-native-push-notification:compileReleaseJavaWithJavac FAILED
/Users/mac/Documents/RNProjects/immigreat-mobile/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:39: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid
/Users/mac/Documents/RNProjects/immigreat-mobile/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:40: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
/Users/mac/Documents/RNProjects/immigreat-mobile/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:143: error: cannot find symbol
              .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                                            ^
  symbol:   class InstanceIdResult
  location: class RNPushNotification
/Users/mac/Documents/RNProjects/immigreat-mobile/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:145: error: cannot find symbol
                  public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                                       ^

**Comment by nguyendai0208** [comment] 2021-05-12 10:52
Same problem. But I'm using react-native 0.62.2

**Comment by VladyslavLypovets** [comment] 2021-05-12 10:55
Same problem

**Comment by ayaskevich** [comment] 2021-05-12 11:02
Duplicate of #1979

**Comment by raaidkh-tsa** [comment] 2021-05-12 11:14
Same Issuse in 7.0.0

**Comment by tastafur** [comment] 2021-05-12 11:20
yes some problem with react-native 0.63.4

**Comment by Dallas62** [comment] 2021-05-12 11:20
Duplicate of #1979

**Closed by tastafur** 2021-05-12 11:20 UTC
