### ISSUE TITLE
unable to run app  Task :react-native-push-notification:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by raaidkh-tsa** [zo0r/react-native-push-notification#1988] opened 2021-05-12 11:27 UTC
Task :react-native-push-notification:compileDebugJavaWithJavac FAILED
![error](https://user-images.githubusercontent.com/70013991/117967751-0e5ba580-b343-11eb-9902-5f1a369f5fba.JPG)

**Comment by Dallas62** [comment] 2021-05-12 11:32
Please tale a look at issues before opening.
Duplicate of #1979

**Closed** 2021-05-12 11:31 UTC
