### ISSUE TITLE
IOS/Android default sound not working.

### ISSUE THREAD

**Issue by jofax** [zo0r/react-native-push-notification#1485] opened 2020-06-18 02:27 UTC
Hi

I got an issue with remote notification for both ios & android. See details below:

NotificationHandler.js
-------------------------------------------------------------------------------------------
```jsx
import PushNotification from 'react-native-push-notification';
import global from '../utils/global'
class NotificationHandler {
  onNotification(notification) {
    if (typeof this._onNotification === 'function') {
      global.pushMessage = notification.data
      console.log('NotificationHandler is function');
      this._onNotification(notification);
    }
  }

  onRegister(token) {
    console.log('NotificationHandler:', token);

    if (typeof this._onRegister === 'function') {
      this._onRegister(token);
    }
  }

  attachRegister(handler) {
    this._onRegister = handler;
  }

  attachNotification(handler) {
    this._onNotification = handler;
  }
}

const handler = new NotificationHandler();

PushNotification.configure({
  onRegister: handler.onRegister.bind(handler),

  onNotification: handler.onNotification.bind(handler),

  senderID: "*********",

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },

  popInitialNotification: true,
  requestPermissions: true,
});

export default handler;
```
-------------------------------------------------------------------------------------------
NotificationService.js
-------------------------------------------------------------------------------------------
```jsx
import PushNotification from 'react-native-push-notification';
import NotificationHandler from '../utils/NotificationHandler';

export default class NotifService {
  constructor(onRegister, onNotification) {
    this.lastId = 0;

    NotificationHandler.attachRegister(onRegister);
    NotificationHandler.attachNotification(onNotification);

    // Clear badge number at start
    PushNotification.getApplicationIconBadgeNumber(function (number) {
      if (number > 0) {
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
  }

  androidLocalNotification(notificationMessage) {
    PushNotification.localNotification({
      /* Android Only Properties */
      title: 'Test Title', // (optional)
      message: notificationMessage ? notificationMessage : '', // (required)
      playSound: true,
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    });
  }

  checkPermission(cbk) {
    return PushNotification.checkPermissions(cbk);
  }

  requestPermissions() {
    return PushNotification.requestPermissions();
  }

  cancelNotif() {
    PushNotification.cancelLocalNotifications({ id: '' + this.lastId });
  }

  cancelAll() {
    PushNotification.cancelAllLocalNotifications();
  }

  abandonPermissions() {
    PushNotification.abandonPermissions();
  }
}
```

----------------------------------------------------------------------------------
App.js
----------------------------------------------------------------------------------
```jsx
import React, { Component } from 'react';
import { createAppContainer, createSwitchNavigator } from 'react-navigation'
import { createStackNavigator } from 'react-navigation-stack'
import { useNavigation } from '@react-navigation/native'
import {
  Alert,
  AppState,
  Platform
} from 'react-native';

import AsyncStorage from '@react-native-community/async-storage';
import NotificationService from './services/NotificationService'

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    };

    this.appPushNotification = new NotificationService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
    );
  }

 componentDidMount() {
  }

  _storeDeviceID = async (token) => {
    try {
      await AsyncStorage.setItem(
        'DEVICE_UDID',
        token
      );
    } catch (error) {
      console.log('error saving _storeDeviceID');
    }
  };

  onRegister(token) {
    console.log('push token: ' + JSON.stringify(token));
    //DefaultPreference.set('DEVICE_UDID', token.token).then(function () { console.log('done saving device id') });
    this._storeDeviceID(token.token);
    this.setState({ registerToken: token.token, fcmRegistered: true });

  }

  onNotif(notif) {
    if (Platform.OS === 'android') {
      if (typeof (notif.data) !== 'undefined') {
        let msg = notif.data.default;
        this.appPushNotification.androidLocalNotification(msg);
      }
    } 
  }

  handlePerm(perms) {
    console.log('perms: ' + token);
  }
}
```

Here are the response from our Amazon SNS:
**IOS:**
 onNotification: {"foreground":false,"userInteraction":true,"data":{"aps":{"alert":"push message"}}}

**Android:**
onNotification: {"foreground":false,"userInteraction":false,"id":"1031530795","data":{"default":"message from push"}}

Here are my issues:

When I run on IOS on background mode and received a remote notification, the onNotif method doesn't trigger. Whereas on Android, it did log the response from SNS and that I call the user notification method.

Also, both platforms can't play a sound? As you can see on Android, I added a local notification to show and use the default sound but it didn't play. For IOS, I'm totally unsure where to create a local notification as to when the remote push arrived, it already shows when background mode. Is there a way to fix these issues?

I appreciate it if anyone can help.

thanks

**Comment by Dallas62** [comment] 2020-06-18 12:23
Hi @jofax 
Can you reproduce this with the example project ?

Also, can you provide the version of the library ?

**Comment by jofax** [comment] 2020-06-18 12:47
@Dallas62 : here is the version of the library that I used:
"dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/checkbox": "^0.3.0",
    "@react-native-community/push-notification-ios": "^1.2.0",
    "@react-native-firebase/app": "^7.2.0",
    "@react-native-firebase/messaging": "^7.1.5",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.4.2",
    "axios": "^0.19.2",
    "moment": "^2.26.0",
    "moment-timezone": "^0.5.31",
    "node-env-dev": "^1.8.25",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-device-info": "^5.6.1",
    "react-native-event-listeners": "^1.0.7",
    "react-native-push-notification": "^3.5.2",
    "react-native-timeago": "^0.5.0",
  },

For the sample project, I will try to to create a sample source and provide a repository.

**Comment by jofax** [comment] 2020-06-18 22:50
@Dallas62 here is the sample project source:
https://jpatambag@bitbucket.org/jpatambag/pushreactnativeexample.git

**Comment by Dallas62** [comment] 2020-06-18 22:54
Hi,
Your repository is not accessible

**Comment by jofax** [comment] 2020-06-18 23:08
@Dallas62 changing it to public.

**Comment by bastilletech** [comment] 2020-06-22 13:58
Hi,

I see in your exemple project you are using the handler in a component. You MUST set your logic outside of a component to manage background notification.
This is why Notification Handler is outside of the component. In foreground the component is instanciate, this is why it's working.

For iOS, you should refer to:
https://github.com/react-native-community/push-notification-ios

**Comment by Dallas62** [comment] 2020-06-24 10:44
Hi,

As far as I can see, the notification is triggered into a component.
When the application is in background, the component will not be mounted, and the logic inside the component will not be triggered.

To make onNotification works, you must place you logic outside of the component, like into `NotificationHandler`.

**Comment by jofax** [comment] 2020-06-24 11:36
hey @Dallas62 , I was following the example. Can you provide example on it?

**Comment by Dallas62** [comment] 2020-06-24 11:43
Just move your logic inside onNotification of NotificationHandler,
Where you save the data inside « global » and where the console.log is.

**Comment by jofax** [comment] 2020-06-24 11:53
@Dallas62 you mean this?

if (Platform.OS === 'android') {
    if (typeof (notif.data) !== 'undefined') {
        let msg = notif.data.default;
        this.appPushNotification.androidLocalNotification(msg);
    }
    }
}

**Comment by Dallas62** [comment] 2020-06-24 11:56
Yes, moving this into:
NotificationHandler.js
`onNotification`

**Comment by Dallas62** [comment] 2020-06-24 11:58
There is other issues about this, just put your logic outside a component.

**Comment by jofax** [comment] 2020-06-24 12:01
yeah I had the NotifService which is added in the app.js, where I set the onRegister and onNotification @Dallas62 

import AsyncStorage from '@react-native-community/async-storage';
import NotificationService from './services/NotificationService'

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    };

    this.appPushNotification = new NotificationService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
    );
  }

**Comment by Dallas62** [comment] 2020-06-24 12:06
Atlassian BitBucket is not working for me.

From what you said. You must put the notificqtionService outside of the component.
Something like this:


```jsx
import AsyncStorage from '@react-native-community/async-storage';
import NotificationService from './services/NotificationService'



const appPushNotification = new NotificationService();



export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    };
  }
```

The component will not be mount in background and the `App.constructor()` will never be called.

**Comment by jofax** [comment] 2020-06-24 12:12
And then I will put all my logic on the NotificationService @Dallas62?

**Comment by Dallas62** [comment] 2020-06-24 12:15
For logic that runs in every situation, yes.

**Comment by jofax** [comment] 2020-06-24 12:16
Alright, I will try this setup. Will let you know the outcome. Thanks for the help @Dallas62

**Comment by jofax** [comment] 2020-06-25 14:13
@Dallas62, I move all the logic to NotificationService, but I did not get any token nor the service was called. am I missing something? I follow exactly as this:

import AsyncStorage from '@react-native-community/async-storage';
import NotificationService from './services/NotificationService'



const appPushNotification = new NotificationService();

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    };
  }

**Comment by Dallas62** [comment] 2020-06-25 14:31
Can you share NotificationService ?

**Comment by jofax** [comment] 2020-06-25 14:41
Here it is:

import PushNotification from 'react-native-push-notification';
import NotificationHandler from '../utils/NotificationHandler';

export default class NotifService {
  constructor(onRegister, onNotification) {
    this.lastId = 0;

    NotificationHandler.attachRegister(onRegister);
    NotificationHandler.attachNotification(onNotification);

    // Clear badge number at start
    PushNotification.getApplicationIconBadgeNumber(function (number) {
      if (number > 0) {
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
  }

  _storeDeviceID = async (token) => {
    try {
      await AsyncStorage.setItem(
        'DEVICE_UDID',
        token
      );
    } catch (error) {
      console.log('error saving _storeDeviceID');
    }
  };

  _retrieveDeviceID = async () => {
    try {
      const value = await AsyncStorage.getItem('DEVICE_UDID');
      if (value !== null) {
        console.log('APP JS DEVICE_UDID' + value);
        this.setState({
          registerToken: value
        });
      }
    } catch (error) {
      console.log('error getting _retrieveDeviceID');
    }
  };

  onRegister(token) {
    console.log('push token: ' + JSON.stringify(token));
    this._storeDeviceID(token.token);
  }

  onNotif(notif) {
    if (Platform.OS === 'android') {
      if (typeof (notif.data) !== 'undefined') {
        let msg = notif.data.default;
        this.androidLocalNotification(msg);
      }
      EventRegister.emit('showFeedHistoryTab', 'refresh');
    } else {
      EventRegister.emit('showFeedHistoryTab', 'refresh');
    }
  }
  
  androidLocalNotification(notificationMessage) {
    PushNotification.localNotification({
      title: 'Android Push Test',
      message: notificationMessage ? notificationMessage : '', 
      playSound: true,
      soundName: 'chime',
    });
  }

  iosLocalNotification(notificationMessage) {
    PushNotification.localNotification({
      title: 'IOS PUSH TEST',
      message: notificationMessage ? notificationMessage : '',
      playSound: true,
      soundName: 'default',
    });
  }

  checkPermission(cbk) {
    return PushNotification.checkPermissions(cbk);
  }

  requestPermissions() {
    return PushNotification.requestPermissions();
  }

  cancelNotif() {
    PushNotification.cancelLocalNotifications({ id: '' + this.lastId });
  }

  cancelAll() {
    PushNotification.cancelAllLocalNotifications();
  }

  abandonPermissions() {
    PushNotification.abandonPermissions();
  }
}

**Comment by Dallas62** [comment] 2020-06-25 15:00
Hi,

this is because you missed one step.

Change the constructor too to adapt the code.

```jsx
  constructor() {
    this.lastId = 0;

    NotificationHandler.attachRegister(this.onRegister.bind(this));
    NotificationHandler.attachNotification(this.onNotification.bind(this));

    // Clear badge number at start
    PushNotification.getApplicationIconBadgeNumber(function (number) {
      if (number > 0) {
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
  }


```

**Comment by jofax** [comment] 2020-07-14 00:52
@Dallas62 works now, we can close this issue. Thanks for your help!

**Closed** 2021-02-13 13:55 UTC
