### ISSUE TITLE
app does not open/launch when click on notification in the notification tray when app is in background or quit state . i am using react-native-push-notification with cloud messaging v6. After uninstalling react-native-push-notification, it is working fine. But i need to use react-native-push-notification to trigger local notification whenever there is a  foreground notification.

### ISSUE THREAD

**Issue by mohity777** [zo0r/react-native-push-notification#1522] opened 2020-07-10 14:31 UTC
# Question

**Comment by Dallas62** [comment] 2020-07-10 14:47
Since this is not a question but an issue, still the same answer:
Incomplete template, and no information to reproduce such as configuration.
Closing

**Closed by Dallas62** 2020-07-10 14:48 UTC
