### ISSUE TITLE
data not populated on opening local notification

### ISSUE THREAD

**Issue by NicholasIoanJones** [zo0r/react-native-push-notification#1943] opened 2021-04-06 16:17 UTC
I am having a problem with receiving data in a local notification. The original use case created a local notification when the app received a push notification in foreground. To simplify debug though I am now triggering a local notification from a button press in the app. 
       

        const redisplayMessage = {};
        redisplayMessage.title = 'Test Title';
        redisplayMessage.message = 'Test Message';
        redisplayMessage.userInfo = { myDataField: 'ABC', id: 123 };
        PushNotification.localNotification(redisplayMessage);

This displays a local notification and when I tap on it, it is presented to my app but the data presented back to the app is undefined

```
{
    "id": 123,
    "foreground": true,
    "userInteraction": true,
    "message": "Test Message",
    "title": "Test Title",
    "action": "com.apple.UNNotificationDefaultActionIdentifier",
    "data" : undefined
}
```
What am I doing wrong?

**Comment by gitmazzio** [comment] 2021-04-07 08:43
Follow! Same error with iOS devices.

**Comment by gitmazzio** [comment] 2021-04-09 15:46
@NicholasIoanJones did you find a solution?

**Comment by Dallas62** [comment] 2021-04-11 09:45
Duplicate of: https://github.com/zo0r/react-native-push-notification/issues/1488

https://github.com/zo0r/react-native-push-notification/issues/1488#issuecomment-812868878

**Closed by Dallas62** 2021-04-11 09:45 UTC

**Comment by nachoperez714** [comment] 2021-08-30 17:34
I dont think this is a duplicate of [#1488 comment](https://github.com/zo0r/react-native-push-notification/issues/1943#:~:text=Duplicate%20of%3A%20%231488-,%231488%20(comment),-Dallas62%20closed%20this). It doesnt solve the issue for me.
