### ISSUE TITLE
Action buttons not showing when the app is on kill-state 

### ISSUE THREAD

**Issue by akiladevinda** [zo0r/react-native-push-notification#2049] opened 2021-06-14 10:35 UTC
I have implemented Action Buttons for Android and when the app is on kill state action buttons are not showing

**Comment by Dallas62** [comment] 2021-06-14 10:58
I have implemented Action Buttons for Android and when the app is on kill state action buttons are showing

**Comment by Dallas62** [comment] 2021-06-14 10:58
Please provide a full reproduction exemple or I will just closed this issue.

**Comment by akiladevinda** [comment] 2021-06-15 02:50
@Dallas62  here's my code

My FCM Helper File Listners 

```
  createNotificationListeners = (
    onRegister,
    onNotification,
    onOpenNotification,
  ) => {
    // When the application is running, but in the background
    messaging().onNotificationOpenedApp((remoteMessage) => {
      console.log(
        '[FCMService] onNotificationOpenedApp Notification caused app to open from background state:',
        remoteMessage,
      );
      if (remoteMessage) {
        let notification = null;
        let data = remoteMessage.data;
        let openFromKilling = {"checked" : true}
        notification = remoteMessage.notification;
        notification.data = data;
        notification.checking = openFromKilling;
        onOpenNotification(notification);
      }
    });

    // When the application is opened from a quit state.
    messaging()
      .getInitialNotification()
      .then((remoteMessage) => {
        console.log(
          '[FCMService] getInitialNotification Notification caused app to open from quit state:',
          remoteMessage,
        );

        if (remoteMessage) {
          let notification = null;
          let data = remoteMessage.data;
          let openFromKilling = {"checked" : true}
          notification = remoteMessage.notification;
          notification.data = data;
          notification.checking = openFromKilling;
          onOpenNotification(notification);
        }
      });

    // Foreground state messages
    this.messageListener = messaging().onMessage(async (remoteMessage) => {
      console.log(
        '[FCMService] A new FCM message arrived! foreground',
        remoteMessage,
      );
      if (remoteMessage) {
        let notification = null;
        let data = remoteMessage.data;

        if (Platform.OS === 'ios') {
          notification = remoteMessage.notification;
        } else {
          notification = remoteMessage.notification;
        }
        notification.data = data;
        onNotification(notification);
        // onOpenNotification(remoteMessage.data);
      }
    });
    // Triggered when have new token
    // messaging().onTokenRefresh((fcmToken) => {
    //   alert('REFRESH TOKEN');
    //   console.log('[FCMService] New token refresh: ', fcmToken);
    //   onRegister(fcmToken);
    // });
  };
```

Notification Builder Code

```
  buildAndroidNotification = (
    id,
    title,
    message,
    data = {},
    options = {},
    channel,
    testData
  ) => {
    console.log('TEST DATA -> ',data)
    return {
      showWhen: true,  // This is probably not needed, since default value is TRUE.
      when: new Date().getTime(),
      group: "wapp",
      groupSummary: true,
      channelId: channel,
      id: id,
      autoCancel: true,
      largeIcon: options.largeIcon || 'ic_launcher',
      smallIcon: options.smallIcon || 'ic_launcher',
      bigText: message || '',
      subText: title || '',
      vibrate: options.vibrate || true,
      vibration: options.vibration || 300,
      priority: options.priority || 'high',
      importance: options.importance || 'high', // (optional) set notification importance, default: high,
      data: data,
      actions:testData,
      // invokeApp:false,
    };
  };
```


In my index.js I have a background msg handler and this function only calls when I was on the killing state

```
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log('Message handled in the background!', remoteMessage);
});
```


I have passed the action button like this onNotification function

 ```
   function onNotification(notify) {
      var RandomNumber = Math.floor(Math.random() * 100) + 1;
      console.log(
        '🚀 ~ file: Router.js ~ line 309 ~ onNotification ~ notify',
        notify,
      );
      let actionData = [];

      if(Platform.OS == 'android'){
        if(notify.title == 'Phone number update'){
          actionData = ["Update contact number"]
        }else if(notify.data.click_action == 'account_edit'){
          actionData = ["Update Email"]
        }else if(notify.data.click_action == 'sign_in'){
          actionData = ["Sign in with this device","Sign into website"]
        }else if(notify.data.click_action == 'payment_method'){
          actionData = ["Update payment method"]
        }else if(notify.data.click_action == 'billing_history'){
          actionData = ["View billing history"]
        }else if(notify.data.click_action == 'help'){
          actionData = ["Contact us"]
        }else if(notify.data.click_action == 'manage_people_on_policy'){
          actionData = ["Manage passengers"]
        }else if(notify.data.click_action == 'my_policy'){
          actionData = ["View policy"]
        }else if(notify.data.click_action == 'ontrip_dashboard'){
          actionData = ["Manage your trip cover"]
        }else if(notify.data.click_action == 'trip_history'){
          actionData = ["See my Trip History"]
        }else if(notify.data.click_action == 'location_disable'){
          actionData = ["Not yet","Activate"]
        }else if(notify.data.click_action == 'rate_wapp'){
          actionData = ["Yes, sure!","Remind me later","No, thanks"]
        }else if(notify.data.click_action == 'help_screen'){
          actionData = ["Contact us"]
        }else if(notify.title == 'Phone number update'){
          actionData = ["Update contact number"]
        }
      }

      const options = {
        soundName: 'default',
        playSound: true,
      };
      localNotificationService.showNotification(
        RandomNumber,
        notify.title,
        Platform.OS == 'android' ? notify.body : notify.body,
        notify,
        options,
        'wapp',
        actionData
      );
    }
```

**Comment by akiladevinda** [comment] 2021-06-15 03:52
I have implemented an action button according to click action of notification on onNotification function. But when I was on the kill state app-only fire messaging().setBackgroundMessageHandler function and does not go to onNotification function

**Comment by akiladevinda** [comment] 2021-06-15 05:00
@Dallas62  any help ?

**Comment by akiladevinda** [comment] 2021-06-15 05:16
@Dallas62  issue is onNotification not calling once the background or killed state. Any help would be appreiciate

**Comment by Dallas62** [comment] 2021-06-15 05:47
There is no code related to the library, only the trigger function.
RNFirebase will not catch actions of this library.
Only `.configure()` will.
Refer to exemple project.

**Closed** 2021-06-15 05:47 UTC

**Comment by akiladevinda** [comment] 2021-06-15 05:50
@Dallas62  can you please tell me how to fix this ? onNotification getting called when app is in foreground

**Comment by akiladevinda** [comment] 2021-06-15 05:50
@Dallas62  can you please tell me how to fix this ? onNotification getting called when app is in foreground

**Comment by Dallas62** [comment] 2021-06-15 05:52
Already answered, refer to exemple project

**Comment by nabilfreeman** [comment] 2021-06-29 15:34
Impossible to trigger background handler in kill state (swipe up to close). The app will wake up and trigger when killed for performance reasons by iOS. If the user killed the app everything will work again next time they open it.

Very hard to debug / build for push actions because of this behaviour
