### ISSUE TITLE
LocalNotificationSchedule misbehaviour in Android 10

### ISSUE THREAD

**Issue by Jacky9425** [zo0r/react-native-push-notification#1259] opened 2019-12-10 01:23 UTC
I've fired a few scheduled local notifications on user opened the app. Works fine on android 8 test phone but when installed onto a phone with android 10, the notifications doesnt come in as expected. Only when i open the app, all the past notifications come in together. 

Anyone facing this issue and have an explanation? thanks

**Comment by Jacky9425** [comment] 2019-12-10 08:59
Sample code to reproduce (Android 10 only, if you're a OnePlus user please try this on the device)

```
let intervals = [0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30];

this.intervals.map(item => {
     PushNotification.localNotifcationSchedule({
           title: "some_title",
           message: "some_message",
           date: new Date(moment(some_date).valueOf() + item * 1000)
     })
});
```

EXPECTED: all notifications fires continuously at time 12.00.02 to 12.00.30 (dummy data)

RESULT: no notifications are fired within 12.00 to 12.00.30, only fires all 30 at once when open app

Anyone with similar test results or different results are welcome to share your opinion here thanks

**Comment by Paranpreet** [comment] 2019-12-19 20:25
+1 localNotifcationSchedule triggered push as soon as button clicked to schedule notification.

**Comment by dimonchik-com** [comment] 2020-01-10 13:41
Any news?

**Comment by Ro4ch** [comment] 2020-01-22 07:53
I am having this issue as well.

**Comment by odeszaxoxo** [comment] 2020-01-30 10:46
Someone fix this issue? Or can help with it? Same problem at Android 8-9 emulators and Android 8 device.

**Comment by Dallas62** [comment] 2020-04-14 13:38
Hi!
Someone is able to try if add the permission:
```xml
 <uses-permission android:name="com.android.alarm.permission.SET_ALARM"/>
```
Solve this issue ?
I will investigate on this.

**Comment by Dallas62** [comment] 2020-04-15 07:34
```js
  scheduleNotif() {
    let intervals = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30];

    intervals.map((item) => {
      PushNotification.localNotificationSchedule({
        title: 'some_title',
        message: 'some_message',
        date: new Date(Date.now() + item * 1000),
      });
    });
  }
```
I tested this code on Android 10 release mode, I'm not able to reproduce it.

Can you try to add an ìd` to your notification if it occurs ?

**Comment by Dallas62** [comment] 2020-07-08 11:06
Since there is no more activity on this issue, I'm closing it, feel free to reopen if you have more information.

**Closed by Dallas62** 2020-07-08 11:06 UTC

**Comment by amaljosea** [comment] 2021-01-30 05:53
I have this issue 2021

**Comment by Decezaris** [comment] 2021-08-06 01:55
The problem still remains, I'm using samsung s10 device and all notifications are fired at once :/
