### ISSUE TITLE
onNotification is not calling when app is in background

### ISSUE THREAD

**Issue by rizwanshaikh199091** [zo0r/react-native-push-notification#1431] opened 2020-05-11 08:40 UTC
# Bug
When I am calling fcm server push notification api data is not showing on onNotification function.

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: 3.4.0

## Steps To Reproduce
I use the following code for recieving push notification

1. Call the service from postman collection for fcm
2. we got data in onNotification when app is in foreground but not in backgorund
...

Describe what you expected to happen:

1.
2.

## Reproducible sample code
PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: function (token) {
        console.log("TOKEN:", token);
        thats.setState({deviceToken:token});
      },
    
      // (required) Called when a remote or local notification is opened or received
      onNotification: function (notification) {
        

        console.log('** NOTIFICATION: **', notification);

      if (Platform.OS === 'ios') {
        if (notification.alert.length !== 0) {
          //handleNotification(notification)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
      } else {
        //handleNotification(notification)
      }

      
      },
    
      // IOS ONLY (optional): default: all - Permissions to register.
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
    
      // Should the initial notification be popped automatically
      // default: true
      popInitialNotification: true,
    
     
      requestPermissions: true,
    });

    PushNotification.popInitialNotification((notification) => { 
      console.log(notification); 
    })

**Comment by Dallas62** [comment] 2020-05-11 09:04
Hi @rizwanshaikh199091 
Can you provide more information ?
Where did you put `PushNotification.configure` ? Inside a component ?
Can you reproduce it in example project ?

**Comment by rizwanshaikh199091** [comment] 2020-05-11 11:14
Hi @Dallas62 

Thanks for quick reply, I put my code inside constructor function. 

This is the code that I put inside constructor function of my call and calling api from postman.

`
    PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: function (token) {
        console.log("TOKEN:", token);
        thats.setState({deviceToken:token});
      },
    
      // (required) Called when a remote or local notification is opened or received
      onNotification: function (notification) {
        

        console.log('** NOTIFICATION: **', notification);

      if (Platform.OS === 'ios') {
        if (notification.alert.length !== 0) {
          //handleNotification(notification)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
      } else {
        //handleNotification(notification)
      }

      
      },
    
      // IOS ONLY (optional): default: all - Permissions to register.
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
    
      // Should the initial notification be popped automatically
      // default: true
      popInitialNotification: true,
    
     
      requestPermissions: true,
    });

    PushNotification.popInitialNotification((notification) => { 
      console.log(notification); 
    })`

I have attached a few screenshots taken in both the conditions. Please have a look.
<img width="952" alt="Screenshot 2020-05-11 at 4 39 11 PM" src="https://user-images.githubusercontent.com/20221070/81555612-8432d700-93a6-11ea-90f3-187192622282.png">

<img width="565" alt="Screenshot 2020-05-11 at 4 39 49 PM" src="https://user-images.githubusercontent.com/20221070/81555646-8f860280-93a6-11ea-8f7e-8fac852d218e.png">


<img width="1315" alt="Screenshot 2020-05-11 at 4 42 22 PM" src="https://user-images.githubusercontent.com/20221070/81555676-9876d400-93a6-11ea-9a1e-b6fe1349997d.png">

Please advice. Thanks

**Comment by Dallas62** [comment] 2020-05-11 11:17
> Hi @Dallas62
> 
> Thanks for quick reply, I put my code inside constructor function.
> 
> This is the code that I put inside constructor function of my call and calling api from postman.
> 
> ```js-jsx
>     PushNotification.configure({
>       // (optional) Called when Token is generated (iOS and Android)
>       onRegister: function (token) {
>         console.log("TOKEN:", token);
>         thats.setState({deviceToken:token});
>       },
>     
>       // (required) Called when a remote or local notification is opened or received
>       onNotification: function (notification) {
>         
> 
>         console.log('** NOTIFICATION: **', notification);
> 
>       if (Platform.OS === 'ios') {
>         if (notification.alert.length !== 0) {
>           //handleNotification(notification)
>           notification.finish(PushNotificationIOS.FetchResult.NoData);
>         }
>       } else {
>         //handleNotification(notification)
>       }
> 
>       
>       },
>     
>       // IOS ONLY (optional): default: all - Permissions to register.
>       permissions: {
>         alert: true,
>         badge: true,
>         sound: true,
>       },
>     
>       // Should the initial notification be popped automatically
>       // default: true
>       popInitialNotification: true,
>     
>      
>       requestPermissions: true,
>     });
> 
>     PushNotification.popInitialNotification((notification) => { 
>       console.log(notification); 
>     })
> ```
> 
> I have attached a few screenshots taken in both the conditions. Please have a look.
> <img alt="Screenshot 2020-05-11 at 4 39 11 PM" width="952" src="https://user-images.githubusercontent.com/20221070/81555612-8432d700-93a6-11ea-90f3-187192622282.png">
> 
> <img alt="Screenshot 2020-05-11 at 4 39 49 PM" width="565" src="https://user-images.githubusercontent.com/20221070/81555646-8f860280-93a6-11ea-8f7e-8fac852d218e.png">
> 
> <img alt="Screenshot 2020-05-11 at 4 42 22 PM" width="1315" src="https://user-images.githubusercontent.com/20221070/81555676-9876d400-93a6-11ea-9a1e-b6fe1349997d.png">
> 
> Please advice. Thanks

I think you should put the  `PushNotification.configure` Outside of a component,
Take a look at [example](https://github.com/zo0r/react-native-push-notification/blob/master/example/NotificationHandler.js)

**Comment by rizwanshaikh199091** [comment] 2020-05-11 11:29
Okay let me try this

**Comment by davidsalib** [comment] 2020-05-11 22:11
I'm having the same issue.

**Comment by Dallas62** [comment] 2020-05-12 06:12
> Okay let me try this

I didn't notice, but in your screenshot there is the `data`, which means you received the notification, so everything is OK, no ?

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

> onMessageReceived is provided for most message types, with the following exceptions:
>
> **Notification messages delivered when your app is in the background:** In this case, the notification is delivered to the device’s system tray. A user tap on a notification opens the app launcher by default.
>
> **Messages with both notification and data payload, when received in the background:** In this case, the notification is delivered to the device’s system tray, and the data payload is delivered in the extras of the intent of your launcher Activity.
>
>
>App state | Notification | Data | Both
>-- | -- | -- | --
>Foreground | onMessageReceived | onMessageReceived | onMessageReceived
>Background | System tray | onMessageReceived | Notification: system trayData: in extras of the intent.

I know this is not what you expect, but I don't think we can change this.

**Comment by taymer** [comment] 2020-05-19 16:04
Same issue here, I tried with the example app and onNotification is always called except when app is in backgroud.
The App is just cloned from git example.
I'm trying it in an Android 7.0 device

**Comment by taymer** [comment] 2020-05-19 17:04
Ok, i figured it out: the problem is that onNewIntent() is not called on ReactContextBaseJavaModule
This solution worked in the example app: https://stackoverflow.com/a/45749359/829300

I modified `public class RNPushNotification` implementing Application.ActivityLifecycleCallbacks and overriding `
    public void onActivityStarted(Activity activity) {
        Intent intent = activity.getIntent();
        Bundle bundle = this.getBundleFromIntent(intent);
        if (bundle != null) {
            bundle.putBoolean("foreground", false);
            intent.putExtra("notification", bundle);
            mJsDelivery.notifyNotification(bundle);
        }
    }`

**Comment by wbercx** [comment] 2020-05-24 23:20
> ```
> public void onActivityStarted(Activity activity) {
>     Intent intent = activity.getIntent();
>     Bundle bundle = this.getBundleFromIntent(intent);
>     if (bundle != null) {
>         bundle.putBoolean("foreground", false);
>         intent.putExtra("notification", bundle);
>         mJsDelivery.notifyNotification(bundle);
>     }
> }
> ```

@taymer This appears to be a source of crashes now. I've received the following stacktrace a number of times over the weekend (Release build). 

I assume this means `mJsDelivery` may not always be initialised when `onActivityStarted` runs.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dieam.reactnativepushnotification.modules.d.c(android.os.Bundle)' on a null object reference
  at com.dieam.reactnativepushnotification.modules.RNPushNotification.onActivityStarted(RNPushNotification.java:5)
  at android.app.Application.dispatchActivityStarted(Application.java:406)
  at android.app.Activity.dispatchActivityStarted(Activity.java:1239)
  at android.app.Activity.onStart(Activity.java:1724)
  at androidx.fragment.app.d.onStart(FragmentActivity.java:1)
  at androidx.appcompat.app.e.onStart(AppCompatActivity.java:1)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
  at android.app.Activity.performStart(Activity.java:7848)
  at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Dallas62** [comment] 2020-05-25 06:09
Hi @wbercx 
Can you provide the `android:launchMode` of your activity ?

**Comment by wbercx** [comment] 2020-05-25 07:06
@Dallas62 `singleTop`. 

I do not remember the exact reason why though. I feel like I've had to mess with that a few times over the years. I wrote a particularly useless commit message for that too...

**Comment by Dallas62** [comment] 2020-05-25 07:11
@wbercx 
Ok, I reverted the PR and changed the code in the JS side, this might be good.
I do more tests and release a fix ASAP

**Comment by wbercx** [comment] 2020-05-25 07:12
@Dallas62 Have a look at the above, I edited it just moments earlier.

**Comment by Dallas62** [comment] 2020-05-25 07:15
@wbercx This is not a good solution anyway, this cause a bug on background by triggering the notification again and again when you switch from background / foreground state. #1455 
The check in the JS side is not enough to handle properly the `popInitialNotitication` it's just a boolean, once it's `true` nothing can be done.
I switched to the id of the notification but I need to check iOS.

**Comment by AndersonSchmidt** [comment] 2020-06-09 14:24
Is this fixed? It's not working for me either.

**Comment by Dallas62** [comment] 2020-06-09 18:26
Hi @AndersonSchmidt 
The main reason this is not triggered on Android is that you put `.configure` inside a component.
Move it outside of a component and this should work.

**Comment by AndersonSchmidt** [comment] 2020-06-09 19:28
@Dallas62 First of all, thank you for your response. I already tried to do it like this: https://i.imgur.com/hd9NyNM.png on my App.js. It only calls onNotification if the app is in Foreground. If I exit or navigate to another app, I receive the notification but onNotification is not called. I'm using the version 3.5.1. I don't know what to do anymore, I spent all day trying to fix this. I would be really glad if you have some solution for me. Thanks.

**Comment by Dallas62** [comment] 2020-06-09 19:34
In another issue:
Can you provide `AndroidManifest` ?
Also try to clean Android build cache and upgrade to 3.5.2.

**Comment by AndersonSchmidt** [comment] 2020-06-09 19:46
@Dallas62 
![image](https://user-images.githubusercontent.com/32553792/84192671-b6505b00-aa70-11ea-93bc-e5134b706bd5.png)

**Comment by taymer** [comment] 2020-06-09 20:38
@Dallas62 what version of android are your device ? I've still the same issue with 7.0

**Comment by AndersonSchmidt** [comment] 2020-06-09 20:41
@taymer But didn't you manage to solve it? Your solutions were even merged, but I saw that it's removed on version 3.5.2. By the way, I test on android 8 and 10 and it's not working.

**Comment by taymer** [comment] 2020-06-09 21:03
@AndersonSchmidt I've tried 3.5.2, but I'm still using my piece of code, which works with the app in background, but not if it's closed (it calls onNotification only if you put the app in background and then again in foreground) . Sadly for now I've not enough time to check this issue.

**Comment by AndersonSchmidt** [comment] 2020-06-09 21:10
@taymer I understand. Do you have any tips/suggestions for me? I need to call onNotification ALWAYS when a notification is received to update a redux state to add a notification badge number on my hamburger button, so the user will know if and how many notifications he has. I was progressing well but got stuck on this. <a href="https://react-native-elements.github.io/react-native-elements/docs/badge.html">Check the badge I'm using.</a>

**Comment by taymer** [comment] 2020-06-10 07:30
@AndersonSchmidt I've just tried the example app with version 3.5.2 and it works like a charm, so the problem is in our use of the library

**Comment by Dallas62** [comment] 2020-06-10 08:26
I will retest this at the end of the day.
The main reason of this problem is when you try to manage the callback of `onNotification` inside a component.

**Comment by Dallas62** [comment] 2020-06-10 08:28
Also check the `launchMode` of your AndroidManifest @AndersonSchmidt in example project the value is `singleTop`.

**Comment by taymer** [comment] 2020-06-10 09:49
@Dallas62 In the example inside the library the launch mode is `singleTask`

**Comment by AndersonSchmidt** [comment] 2020-06-10 11:48
> @Dallas62 First of all, thank you for your response. I already tried to do it as the image shows. It only calls onNotification if the app is in Foreground. If I exit or navigate to another app, I receive the notification but onNotification is not called. I'm using version 3.5.1. I don't know what to do anymore, I spent all day trying to fix this. I would be really glad if you have any solution for me. Thanks.
> ![hd9NyNM](https://user-images.githubusercontent.com/32553792/84191175-7daf8200-aa6e-11ea-8d89-d0915fe47d25.png)

@taymer @Dallas62 Am I doing it right here?

**Comment by Dallas62** [comment] 2020-06-11 06:35
This is why `onNotification` is not trigger.
Look at my previous message.

You can’t use `notification` field with background handler.
You must use `data` (and not combined with `notification`).
Then if you want to notify the user, trigger a local notification.

**Comment by mehul2013** [comment] 2020-06-11 18:15
I am facing the same kind of issue on the android phone. I have used scheduleLocalNotificaiton in my application.
Follow the below steps in an example(the demo project which is given in this repo) of **android app**:
1. Launch the app
2. Click on Schedule notification for 30 seconds
3. Now click on the **hardware back button** to make the app in the background
4. Now notification will come and click on it.
5. App will open again but **Alert will not display means onNotification method does not fire**

I have spent more than 8 hours to resolve this issue but can't succeed. Is there any way to fix this issue?

**Comment by Dallas62** [comment] 2020-06-11 20:02
Hi @mehul2013 
On the current version of the library, scheduled notification doesn't trigger `onNotification`.
You can test the version on `dev` branch but some changes will be made before the release.
I try to update the `CHANGELOG.md` on `dev` as soon as changes are made.

**Comment by AndersonSchmidt** [comment] 2020-06-12 21:19
> This is why `onNotification` is not trigger.
> Look at my previous message.
> 
> You can’t use `notification` field with background handler.
> You must use `data` (and not combined with `notification`).
> Then if you want to notify the user, trigger a local notification.

Thank you @Dallas62! That was the problem. It's working perfect now.

**Comment by Faolain** [comment] 2020-06-21 08:18
> This is why `onNotification` is not trigger.
> Look at my previous message.
> 
> You can’t use `notification` field with background handler.
> You must use `data` (and not combined with `notification`).
> Then if you want to notify the user, trigger a local notification.

@Dallas62  Really appreciate this explanation and just want to clarify if I have this correct. If I do a remote notification while the application is in the Foreground onNotification will be called, but if the app is in the background or closed onNotification will not be called with a regular remote notification and instead one must send a silent notification (only data, empty notification) and this will be processed in the onNotification callback(with the information available on data)?  

I have a similar situation as @AndersonSchmidt where I need to add information to my redux store from another user messaging so I need to ensure the notification causes this data to be processed.

Thanks again! If this question is not clear please let me know.

**Comment by Dallas62** [comment] 2020-06-21 08:36
Hi,
If you want a background process in any cases, you must send data-only notification.
This way you should be able to trigger a local notification and run your process.
Persist your state at the end of the process.
Long process are not allowed (not sure but it’s <10/20s), prefer send data in notification than requesting a server when possible.

**Comment by Faolain** [comment] 2020-06-21 09:03
Thank you so much @Dallas62 that worked exactly like you said! If you would like me to add this information to the README I would be more than happy to do so in a PR let me know! :)

**Comment by Dallas62** [comment] 2020-06-21 17:38
You can make a PR if you want, this is from the official documentation of Firebase

**Comment by kirantripathi** [comment] 2020-08-25 12:28
@AndersonSchmidt  @Dallas62  , I try to use onNotificaiton property but it only works when app is in foreground , not in background. can you guys tell me what may be the issues?
<img width="1247" alt="Screen Shot 2020-08-25 at 18 12 05" src="https://user-images.githubusercontent.com/17666887/91174111-8c691500-e6fe-11ea-8500-56a20ddcada1.png">

**Comment by Dallas62** [comment] 2020-08-25 13:25
Hi @kirantripathi 

https://github.com/zo0r/react-native-push-notification/issues/1431#issuecomment-642441772

**Comment by kirantripathi** [comment] 2020-08-26 05:51
<img width="643" alt="Screen Shot 2020-08-26 at 11 34 12" src="https://user-images.githubusercontent.com/17666887/91263701-2331e200-e790-11ea-9d8d-3f570ebae2ca.png">
@Dallas62 thanks for that, now I am getting notification response in  onNotification callback, but when I click notification  "userInteraction" key is still false and I am not able to perform any operation on it. I need to perform some operation when click on notification.so for that what should I do . can you help me on that?

**Comment by naveenprakash74** [comment] 2020-09-03 14:42
> This is why `onNotification` is not trigger.
> Look at my previous message.
> 
> You can’t use `notification` field with background handler.
> You must use `data` (and not combined with `notification`).
> Then if you want to notify the user, trigger a local notification.

I am still facing this problem. can you give some example code? Thank you

**Comment by romelbonnie** [comment] 2020-11-16 09:08
> This is why `onNotification` is not trigger.
> Look at my previous message.
> 
> You can’t use `notification` field with background handler.
> You must use `data` (and not combined with `notification`).
> Then if you want to notify the user, trigger a local notification.

I've followed this process. I sent data-only and trigger a local notification. But when I press the notification it will trigger another local notification. Can you please give an example on how you implement receiving remote notifications and trigger local notification.

**Comment by romelbonnie** [comment] 2020-11-16 09:56
Oh I see. Thank you @Dallas62

**Comment by ehsanmolaei991** [comment] 2020-11-29 12:32
![2020-11-29 15_54_54-App js - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100541777-61d9ab80-325b-11eb-87aa-a537c4cf56a6.png)
![2020-11-29 15_55_17-App js - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100541778-630ad880-325b-11eb-8852-1bae4c3a1fab.png)

@Dallas62 
Please give me a solution
i configure PushNotification out of component (Bottom of App Class)
and call localNotification but nothing happened 

but i see "console.log('TOKEN:', token);" in debugger and just it 

please help me !!!

**Comment by Dallas62** [comment] 2020-11-29 12:33
Hi,

There is no channelId defined.

**Closed by Dallas62** 2020-11-29 12:33 UTC

**Comment by ehsanmolaei991** [comment] 2020-11-29 12:43
Tnx Man.

> Hi,
> 
> There is no channelId defined.

Tnx Man

**Comment by ehsanmolaei991** [comment] 2020-11-30 10:06
@Dallas62

**Comment by ehsanmolaei991** [comment] 2020-11-30 10:13
![2020-11-30 13_30_46-AndroidManifest xml - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596226-2c8f9500-3311-11eb-9179-35f00de87b7b.png)
![2020-11-30 13_32_10-AndroidManifest xml - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596234-2e595880-3311-11eb-801f-0d6f5d55638d.png)
![2020-11-30 13_32_25-AndroidManifest xml - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596238-2ef1ef00-3311-11eb-8bde-45200c1af3b9.png)
![2020-11-30 13_32_37-AndroidManifest xml - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596242-30231c00-3311-11eb-8381-ad733441b420.png)
![2020-11-30 13_33_08-NotificationManeger js - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596247-30bbb280-3311-11eb-9252-4379cfea1efe.png)
![2020-11-30 13_35_12-NotificationManeger js - Mutalee - Visual Studio Code](https://user-images.githubusercontent.com/31288305/100596250-31ecdf80-3311-11eb-9399-7bd606e2afb6.png)

@Dallas62 
Hi again 
I can't solve my problem 
I can use local notification for myapp but i can't use remote mode 
I add google service and firebase and google.json in build.gradle and android/app

I use this AndroidManifest
and put this sender Id 

please help me,

**Comment by Dallas62** [comment] 2020-11-30 10:47
Hi @rizwanshaikh199091 
You are using deprecated properties in your AndroidManifest, please refer to the changelog for upgrade your manifest.
Also you don't provide the Payload of the notification, it's not possible to help you without it.

Refer to:
https://firebase.google.com/docs/cloud-messaging/concept-options
and
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#1-local-notifications
For more informations.

Regards,

**Comment by stephanoparaskeva** [comment] 2021-03-30 18:38
I am sending a data notification and the onNotification function is not called when the app is in the background. But it is called when the application is in the foreground.

```js
{
 "to" : "fXJ_A95kTQOqm6koxOFBwh:APA91bEAUKYfn4dUhxa00yKNzs4F0b3nAh8oxXGC3cegOxhI2kCQN0XbZ0elI9M640W4SYllNF_rHQOWm8V1ryaueUN6h9ddfX2n9xfQplAzzRzBxVqDdyLa0Yl7NjigsZtlDqTeVS1i",
 "data" : {
     "initiatorId" : "127167807"
 },
  "priority": "high"
}
```

**Comment by sanatChoubey** [comment] 2021-03-30 18:43
> I am sending a data notification and the onNotification function is not called when the app is in the background. But it is called when the application is in the foreground.
> 
> ```js
> {
>  "to" : "fXJ_A95kTQOqm6koxOFBwh:APA91bEAUKYfn4dUhxa00yKNzs4F0b3nAh8oxXGC3cegOxhI2kCQN0XbZ0elI9M640W4SYllNF_rHQOWm8V1ryaueUN6h9ddfX2n9xfQplAzzRzBxVqDdyLa0Yl7NjigsZtlDqTeVS1i",
>  "data" : {
>      "initiatorId" : "127167807"
>  },
>   "priority": "high"
> }
> ```

hey @stephanoparaskeva 
I got know after a day is that javascript code never run in background you need to be in app so it basically work when you tap notifications or in foreground . 
but this case not applied on android android works in background with headless js. 
Thanks

**Comment by Dallas62** [comment] 2021-03-30 18:44
Hi @stephanoparaskeva 
For iOS, please refer to the iOS repository.
For Android make sure Android Manifest is configured as described in the Readme.

In general, do not put `.configure()` inside a component.
Regards

**Comment by stephanoparaskeva** [comment] 2021-03-30 18:47
@Dallas62 
This is my index.js file:
```js

const onRegister = ({ token }: TDeviceInfo) => AsyncStorage.setItem(FCM_OR_APNS_TOKEN, token);

PushNotification.configure({
  onRegister,
  onNotification,
  popInitialNotification: true,
  requestPermissions: true,
});

const findTokenEvent = (evt: TEvent) =>
  evt.name === VoipPushNotification.RNVoipPushRemoteNotificationsRegisteredEvent;

VoipPushNotification.addEventListener('didLoadWithEvents', (events: Array<TEvent>) => {
  const apnsVoipToken = events.find(findTokenEvent)?.data;
  AsyncStorage.setItem(APNS_VOIP_TOKEN, apnsVoipToken || '');
});


AppRegistry.registerComponent(name, () => app);
```

This is my androidmanifest.xml file:
https://pastebin.com/d9Ut5ZYV

I think it should be correct?

**Comment by Dallas62** [comment] 2021-03-31 05:36
Hi @stephanoparaskeva 
Did you create the channel? By calling `.createChannel(...)` ?

**Comment by stephanoparaskeva** [comment] 2021-03-31 09:03
Hi @Dallas62 
Yes I created the channel, but this did not help, here is the manifest:
```js
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
            android:value="false"/>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="QB_PUSH_NOTIFICATION_CHANNEL" />
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="Channel for Quickblox push notification events" />
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@color/primary" />

        <service android:name="com.quickblox.messages.services.fcm.QBFcmPushInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
```
And here is the channel creation in index.js
```js
  PushNotification.configure({
    onRegister,
    onNotification,
    popInitialNotification: true,
    requestPermissions: true,
  });

  PushNotification.createChannel(
    {
      channelId: 'QB_PUSH_NOTIFICATION_CHANNEL', // (required)
      channelName: 'QB_PUSH_NOTIFICATION_CHANNEL', // (required)
      playSound: false, // (optional) default: true
      soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
    },
    created => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
  );

```

I am sending the notification via Postman and it triggers `onNotification` when the app is in the foreground, but it does not trigger `onNotification` when the app is in the background.

**Comment by Dallas62** [comment] 2021-03-31 09:12
@stephanoparaskeva 
You can try to add the channel as default channel:

```xml
  <meta-data
      android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
      android:value="QB_PUSH_NOTIFICATION_CHANNEL" />
```

If the channel is not created and used, the notification will not work.

**Comment by stephanoparaskeva** [comment] 2021-03-31 09:21
> ```
>   <meta-data
>       android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
>       android:value="QB_PUSH_NOTIFICATION_CHANNEL" />
> ```

I have tried this too and it doesnt work. I have also removed this channel entirely and it doesnt work.
Nothing about the message specifies a channel:
```js
{
 "to" : "fXJ_A95kTQOqm6koxOFBwh:APA91bEAUKYfn4dUhxa00yKNzs4F0b3nAh8oxXGC3cegOxhI2kCQN0XbZ0elI9M640W4SYllNF_rHQOWm8V1ryaueUN6h9ddfX2n9xfQplAzzRzBxVqDdyLa0Yl7NjigsZtlDqTeVS1i",
 "data" : {
     "initiatorId" : "127167807"
 },
  "priority": "high"
}
```
It works in the foreground but does not work in the background. There must some other reason, the request is made via postman and is a data request, it does not specify a `notification` field and it has `data` The android manifest follows the readme, the package is on the latest version and the `configure()` function is run outside of any component.

The data notification is sent via postman but the application never runs the `onNotification` function when the app is closed. It is run successfully when the application is in the foreground.

On IOS I can successfully get the `onNotification` function to run when the app is closed when sending a data/background APNS push.

What have I done wrong on the android side?

**Comment by stephanoparaskeva** [comment] 2021-03-31 09:56
Hi @Dallas62 
Here is the new issue created with the LOGCAT logs and the channel_id:
https://github.com/zo0r/react-native-push-notification/issues/1930

**Comment by Harish-Sankey** [comment] 2021-07-20 08:06
Hi @Dallas62 
Is it compulsory to change `android:launchMode="standard"` to ( singleTop or singleTask ) for this library, since for me onNotification() is not getting called when app is in background (when lauchMode is standard) ?

I am using "react-native-push-notification": "^7.4.0"

**Comment by Arunprabhuk** [comment] 2022-04-07 07:45
how can i create push notification  without using firebase and onesignal?
thanks

**Comment by naveenprakash74** [comment] 2022-04-07 07:56
> 

without firebase you can not create remote push notification

if you want to create local push notifications then you can create it with react native push notification module
