### ISSUE TITLE
Native module cannot be null 

### ISSUE THREAD

**Issue by Developer-Nijat** [zo0r/react-native-push-notification#1161] opened 2019-08-07 12:12 UTC
Platform => IOS
Xcode => v10. 3
React native => v0.60.4
react-native-push-notification => v^3.1.8

Please help. What is the problem?

I think plugin is not working properly with latest version rn 0.60.4

Im tried different solutions but not working. 

pod file

pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'

**Comment by buiquangduc** [comment] 2019-08-07 15:02
I need to switch to v3.1.3 to make it works again.

**Comment by Developer-Nijat** [comment] 2019-08-07 15:33
> I need to switch to v3.1.3 to make it works again.

not fixed,

**Comment by spacewaffle** [comment] 2019-08-07 21:04
Also having this issue on RN 0.60.4 and v3.1.8. I also tried downgrading to v3.1.3 and still having the same problem.

**Comment by spacewaffle** [comment] 2019-08-07 21:14
fixed this issue with the following using v3.1.8.

added this line to Podfile
`pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'`

Then run inside your ios directory
pod install

**Comment by stefoid** [comment] 2019-08-08 00:21
actually I dont think that podfile mod is necccessary, due to autolinking.

the change is due to IOSpush being shifted from core react to 'community'

so you need to include the community one in your package, and change your appdelegate to the new push IOS library.  that should work

**Comment by Developer-Nijat** [comment] 2019-08-08 07:09
This is not good solution, Finally i removed package from project !
Alternatively im using now firebase.notifications()

**Comment by lbnlrnt** [comment] 2019-08-09 03:08
The @spacewaffle solution is working,
Just to complete, you'll have to manually link the PushNotificationIOS like before, following [this](https://facebook.github.io/react-native/docs/pushnotificationios)

Only notice that 

`#import <React/RCTPushNotificationManager.h>`

becomes

`#import <RNCPushNotificationIOS.h>`

And you'll also have to change 

`RCTPushNotificationManager` 

to

`RNCPushNotificationIOS`

everywhere in the copied lines.

**Comment by spacewaffle** [comment] 2019-08-09 03:30
I'm back to the drawing board here. The issue is fixed in ios but breaks in android because of an androidx regression. I can get 3.1.3 to work on android but not ios. The reverse is true for 3.1.8.

**Comment by spacewaffle** [comment] 2019-08-09 03:32
This is the android x issue
https://github.com/zo0r/react-native-push-notification/pull/1095

**Comment by Developer-Nijat** [comment] 2019-08-09 06:44
@lbnlrnt then using 
import PushNotificationIOS from "@react-native-community/push-notification-ios"; ???
but android ?
this is way needed 
 **for ios**
`import PushNotificationIOS from "@react-native-community/push-notification-ios";`
**for android**
`import PushNotification from "react-native-push-notification"; `
This is not good solution
it is cross platform application one package must be working both device

**Comment by owinter86** [comment] 2019-08-12 08:59
@Developer-Nijat if you are using the latest version then `import PushNotification from 'react-native-push-notification';` is now using the `PushNotificationIOS` from the community package, so you do not have to do the two imports, this package does it for you.

You just have to unlink the react native core version and then link the community version and then you can still use `import PushNotification from 'react-native-push-notification';` as before.

**Comment by lbnlrnt** [comment] 2019-08-13 05:47
@Developer-Nijat  The thing is react-native-push-notification carry everything for android side and `react-native link react-native-push-notification` does the linking job for android only (you can notice that with the log being android only). On IOS side, we allways had to manually link the PushNotificationIOS within AppDelegate.m. 
Before, the steps were describe by react native team themself because PushNotificationIOS was a module of react native. Now this package can be found as @react-native-community/push-notification-ios. So you have to follow the steps provided by them, [here](https://www.npmjs.com/package/@react-native-community/push-notification-ios) at section AppDelegate.m but nothing else. 
The big thing is that the naming has changed but it basically the same thing.

To resume:
```
yarn add react-native-push-notification
react-native link react-native-push-notification
yarn add @react-native-community/push-notification-ios
cd ./ios && pod install && cd ..
```
- [this](https://www.npmjs.com/package/@react-native-community/push-notification-ios#appdelegatem)

then you follow the readme file of this ackage from [there](https://github.com/zo0r/react-native-push-notification#android-manual-installation)

And when you will use it you just have to : 

`import PushNotification from 'react-native-push-notification'`

And it works cross platform.

**Comment by huyvm** [comment] 2019-08-15 13:24
Hi, if you still that error, you can keep version 3.1.1 (example not ^3.1.1)

**Comment by Janjiran** [comment] 2019-08-19 10:32
Can you at least add this issue to install section? It's pretty much unusable now with 0.60.X react.

**Comment by cookienawer** [comment] 2019-08-23 09:06
In 
```
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function(token) {
    console.log("TOKEN:", token);
  },

  // (required) Called when a remote or local notification is opened or received
  onNotification: function(notification) {
    console.log("NOTIFICATION:", notification);

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
    notification.finish(PushNotification.FetchResult.NoData);
  },

```

`notification.finish(pushnotificationIOS.FetchResult.NoData);`

"can't find variable pushnotificationIOS".

I have change pushnotificationIOS for PushNotification??

**Comment by jackw01** [comment] 2019-09-04 04:11
Downgrading to 3.1.1 fixed this for me.

**Comment by hoonblizz** [comment] 2019-09-04 17:46
@spacewaffle This solution works for me as well. Thank you.

**Comment by lukewlms** [comment] 2019-10-05 11:30
My upgrade path was a little more involved - [posted here](https://stackoverflow.com/a/58247875/152711).

---

1. Upgrade to latest: `yarn add react-native-push-notification`
2. `yarn add @react-native-community/push-notification-ios`
3. Ensure any references are removed from your Podfile (including commented references, or react-native will still complain)
3. in Xcode, remove RNCPushNotification from General -> Linked Frameworks
4. Remove previous PushNotification code from AppDelegate.m
5. `react-native link @react-native-community/push-notification-ios`
6. If this didn't add code in AppDelegate.m (it didn't in my case) then manually add the code from [their GitHub page](https://github.com/react-native-community/react-native-push-notification-ios)

One more gotcha - when testing that it works, make sure your app is closed or a local notification won't fire.

**Comment by schumannd** [comment] 2019-11-18 13:12
Unfortunately none of the solutions in this thread helped me getting the package to run:

react-native: 61.4
react-native-push-notification: 3.1.9
react-native-push-notification-ios: 1.0.2

I had to:
- revert back to 3.1.3
- use the old react-native/pushnotificationIOS
- fix the androidX [errors by hand ](https://itnext.io/react-native-how-to-handle-an-app-with-both-pre-androidx-and-androidx-dependencies-rn60-bf4df7ea0dd2)
- link libraries manually

Any updates on this issue are appreciated.

**Comment by PavanKumar-sa** [comment] 2019-12-02 15:45
@schumannd Was able to resolve this issue with below given versions 

react-native: 0.61.4
react-native-push-notification: 3.1.9

**For iOS follow below given link**

[Manual updates](https://github.com/react-native-community/react-native-push-notification-ios)

**For Pod Updates:**

cd ios, open Podfile and make below given changes

```
# pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS' ----> Remove 

pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec' ----> Add 
```

After modification to Podfile, run pod install inside **ios** folder.

**Closed** 2020-04-22 20:02 UTC
