### ISSUE TITLE
Callback not triggered when notification is opened and app is killed

### ISSUE THREAD

**Issue by andy9775** [zo0r/react-native-push-notification#161] opened 2016-08-03 03:01 UTC
I'm having an issue with the `onNotification` callback not being called if the app is killed and the notification is clicked. Is there anyway to implement this functionality in the app?

RN -> 0.30.0
react-native-push-notification -> 2.0.2

**Comment by parrunset** [comment] 2016-08-03 13:47
same here

**Comment by jakkra** [comment] 2016-08-08 23:53
Ok, so I managed to work around the issue. However, I'm running a version behind you guys, but it might still work for you.
RN -> 0.29.0
react-native-push-notification -> 2.0.1

```
PushNotification.configure({ popInitialNotification: false, ...})
```

And in my onRegister method, I did:
```
PushNotification.popInitialNotification((notification) => {
      if (notification) { this.handleNotification(notification); }
});
```

**Comment by kfiroo** [comment] 2016-08-10 23:40
@jakkra note that the notification format from `popInitialNotification` is different from the one in `onNotification` because it does not pass through the internal `_onNotification`

**Comment by teyou** [comment] 2016-08-24 17:12
same issue here.. it was fine if the notification was received during app is in background mode.

Only when app is killed, received a notification message then user click on the notification from notification area, the payload data is not transferred to onNotification callback (as below)

```
{ 
  foreground: false,
  userInteraction: true,
  message: undefined,  // <---  bug???
  data: undefined,  // <---  bug???
  badge: undefined,
  alert: undefined,
  sound: undefined 
}
```

**Comment by japesh** [comment] 2016-12-24 10:28
This problem can be solved by making some changes in native code.

In RNPushNotification.java file implement **LifecycleEventListener** like this:

public class RNPushNotification extends ReactContextBaseJavaModule implements ActivityEventListener,LifecycleEventListener {
    public RNPushNotification(ReactApplicationContext reactContext) {
        super(reactContext);
  ....
  
        reactContext.addLifecycleEventListener(this);
.... 
  }
 ...
.@Override
    public void onHostResume() {
        Activity activity = getCurrentActivity();
        if (activity != null) {
            Intent intent = activity.getIntent();
            Bundle bundle = intent.getBundleExtra("notification");
            if (bundle != null) {
                bundle.putBoolean("foreground", false);
                bundle.putBoolean("userInteraction", true);
                mJsDelivery.notifyNotification(bundle);
            }
        }
    }

    @Override
    public void onHostPause() {
        // Activity `onPause`
    }

    @Override
    public void onHostDestroy() {
        // Activity `onDestroy`
    }
...
}
That's all and onNotification callback will be triggered everytime

**Comment by npomfret** [comment] 2016-12-24 23:06
@japesh thanks for this.  Would you like to submit a PR with it in?  If so, in the description it would be helpful if you could include a detailed description of the expected change in behaviour and how to test it.

**Comment by japesh** [comment] 2016-12-26 05:46
hey @npomfret 
this module works amazingly, but i am getting problem when app is closed completely. In this case the **on notification function get trigger only ones**, when notification is received. but when app is in background it trigger two times first when notification is received and second time when you click on notification.

the problem is that RNPushNotification class implements ActivityEventListener, and when application is closed their is no activity. Therefore there is no meaning of receiving call in onNewEvent function, that's what i think.

here comes the role of LifecycleEventListener it triggers it's function according to life events of activity. it trigger it's onresume function when the activity get open. therefore what is happening in onNewIntent function, i implemented in on resume function also. 

in this way i start getting call in onNotification function when app is closed, both times first when i receive the notification and second when notification is clicked.

I will make a pull request if it worth. 
thank you

**Comment by kfiroo** [comment] 2016-12-26 13:49
@japesh Hey, just to make sure I'm getting this right, when I receive a notification and the app is `closed`,  `react-native-push-notification` native code is runs in order to build a notification object and place it in the `notification centre`.
Now if I click this notification the app is started and the notification is available in `popInitialNotification`.
Is this not the desired behaviour?
What is the other **trigger** I'm missing?

**Comment by japesh** [comment] 2016-12-26 17:16
@kfiroo but i was getting null in popInitialNotification.

**Comment by npomfret** [comment] 2017-01-31 12:32
I believe this is implemented for android now, but cannot possible work on iOS.  Can we close the issue?

**Comment by toninho** [comment] 2017-04-05 21:38
@japesh Hi, your trick worked for me when clicking notification in background. However, when the app is in foreground, clicking notification is calling onNotification callback twice. 
Did you have experimented this issue?

**Comment by japesh** [comment] 2017-04-06 02:58
Have you checked their ids, are they belong to same notification or different.

**Comment by toninho** [comment] 2017-04-06 12:13
@japesh Hi, they are different notifications. First, the app is in background mode (killed), so I send a PN, onMessage is called, I click notification, the app opens and onMessage is called again (with userInteraction=true).
After, I just close the app, and send a new PN, onMessage is called just for that new notification, but when I clicked the notification the app opens and onMessage is called twice, one time for the first notification and again for the new one.

**Comment by japesh** [comment] 2017-04-06 12:49
I was getting same issue in that if we open app for the first time it was maintaining the state of first notification. For that I worked on the basis unique I'd. Whatever your functionality is, implement it only when you receive a unique Id. For that you can use an array of ids which have been used for opening notification.

**Comment by toninho** [comment] 2017-04-06 13:13
Maybe it's happening because this? #281

**Comment by japesh** [comment] 2017-04-06 13:46
You can confirm it by checking the id of notification. When i check, one of the notification Id was always same and that is of initial notification, that is notification received when your app is not even in background.

**Comment by theohdv** [comment] 2017-07-07 13:15
Any final solution for @japesh trick ?

**Comment by syardumi** [comment] 2017-07-07 14:56
@theohdv same for me. I'm not getting any onNotification when app is bg or closed either.

**Comment by syardumi** [comment] 2017-07-07 15:45
@theohdv Can you post code snippets for your local notifications working correctly? Right now, that's all I'm using, but I still don't have onNotification called.

**Comment by theohdv** [comment] 2017-07-07 15:54
```javascript
PushNotification.localNotificationSchedule({
 message: "My Notification Message", // (required)
 date: new Date(Date.now() + (10 * 1000)) // in 10 secs
});
```

**Comment by syardumi** [comment] 2017-07-07 16:39
I have similar code to trigger the notification. How about onNotification or any tweaks you made to Android manifest or native code? RNPN version? RN version?

Much obliged.

**Comment by theohdv** [comment] 2017-07-07 16:54
I did not change the native code.

```json
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
```

You maybe should read the [Troubleshooting doc](https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md). Interesting infos about this module !

**Comment by shrutic** [comment] 2017-07-19 01:24
I am using react native version 0.43.3 and react-native-push notification version 3.0.0. For me the notification inside the popInitialNotification is always null inside iOS device. Any thoughts? 

` public static startConfiguration(userId: string) {
            if (PushNotification !== null) {
                PushNotification.configure({
                    // (required) Called when a remote or local notification is opened or received
                    onNotification: (notification) => {
                        console.log('Notification received');
                        PushNotificationManager.handleNotificationReceived(notification);
                    },
                    onRegister: (tokenObject) => {
                        PushNotification.popInitialNotification((notification) => {
                            if (notification) {
                                PushNotificationManager.handleNotificationReceived(notification);
                            }
                        });
                        let body = {
                            deviceType: Platform.OS,
                            tags: '',
                            token: tokenObject.token,
                            uid: userId,
                        };
                        UserApi.createOrUpdateDeviceToken(body);
                    },
                    popInitialNotification: false,
                    senderID: ServerUtil.FireBaseSenderId,
                });
            }
    }`

The notification inside popInitialNotification is always null. I am calling PushNotificationManager.startConfiguration() inside componentWillMount of my root component.

Any thoughts on what I am missing?

**Comment by nonameolsson** [comment] 2017-09-07 04:00
#170 - I think that I have a similar issue. Please check my comment in the referenced issue

**Closed** 2018-07-04 21:14 UTC

**Comment by eugene-kim** [comment] 2020-01-10 16:56
Hi,@Gp2mv3, why was this issue closed?

**Comment by nollymar** [comment] 2020-04-20 23:29
I have the same issue, onNotification is not called

**Comment by Mura7** [comment] 2020-04-22 08:19
> I have the same issue, onNotification is not called

+1 for only Ios

**Comment by Dallas62** [comment] 2020-04-22 08:56
Hi @Mura7 
Are you sure it's related to this library ?
Take a look at [push-notification-ios](https://github.com/react-native-community/push-notification-ios/issues).

**Comment by Dallas62** [comment] 2020-04-22 08:57
Hi @nollymar 
Which plateform you encounter this issue ?
A released has been made, please check the installation guide to be sure it's up to date.
Thanks

**Comment by Mura7** [comment] 2020-04-22 09:13
> Hi @Mura7
> Are you sure it's related to this library ?
> Take a look at [push-notification-ios](https://github.com/react-native-community/push-notification-ios/issues).

Hi @Dallas62 
thanks for fast answer.

local notification was not working for ios. I upgraded the Firebase package(6.4.1-alpha.0). now works. 
Could it be affecting firebase also onNotification function?


Android works.

**Comment by Dallas62** [comment] 2020-04-22 09:49
@Mura7 There is an issue [react-native-community/push-notification-ios#106](https://github.com/react-native-community/push-notification-ios/issues/106) on `addEventListener`.
The library is a simple proxy for this part, and doesn't include iOS specific implementation:
[index.js#L84](https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L84)
```js
this.callNative( 'addEventListener', [ 'notification', this._onNotification ] );
```

**Comment by Dallas62** [comment] 2020-04-22 09:52
And also:
https://github.com/react-native-community/push-notification-ios/issues/102

**Comment by nollymar** [comment] 2020-04-22 15:25
@Dallas62 It happens in iOS

> Hi @nollymar
> Which plateform you encounter this issue ?
> A released has been made, please check the installation guide to be sure it's up to date.
> Thanks

**Comment by Dallas62** [comment] 2020-04-22 15:33
@nollymar So it's the same answer as Mura7:
https://github.com/zo0r/react-native-push-notification/issues/161#issuecomment-617674536

**Comment by yurinmk** [comment] 2021-05-23 14:06
I have this probelam that onNotification is not returning anything after clicking on the notification received. Is there a new solution? I already tried the friend @japesh, but it didn't work.
