### ISSUE TITLE
Unable to Avoid create default channel

### ISSUE THREAD

**Issue by dubiao** [zo0r/react-native-push-notification#1537] opened 2020-07-17 10:44 UTC
#Bug

I added the following line in my <application> tag:
`<meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
          android:value="false"/>`

But the defualt channel aways auto created. 
I've uninstalled and reinstall the app.

**Comment by Dallas62** [comment] 2020-07-17 11:23
Unable to reproduce and doesn't provide information such as version.

Closing...

**Closed by Dallas62** 2020-07-17 11:23 UTC
