### ISSUE TITLE
Cancelling scheduled notification

### ISSUE THREAD

**Issue by abeikverdi** [zo0r/react-native-push-notification#197] opened 2016-09-12 03:21 UTC
I have a `PushNotification.localNotificationSchedule` thats scheduled for a notification some time in future. How can I cancel that?

**Comment by vikeri** [comment] 2016-09-12 15:35
It's being worked on in this PR: https://github.com/zo0r/react-native-push-notification/pull/172

**Comment by npomfret** [comment] 2016-09-12 15:45
@abeikverdi  I've committed to master - would you like to give it a test?

**Comment by vikeri** [comment] 2016-09-13 13:27
@npomfret I can confirm that it works for me

**Comment by npomfret** [comment] 2016-09-13 13:29
Thanks

**Comment by npomfret** [comment] 2016-09-15 09:55
@zo0r i think master is good for an npm release

**Comment by zo0r** [comment] 2016-09-15 19:36
@npomfret just pushed it! **2.1.1**

Thank you for all your collaboration!

**Comment by npomfret** [comment] 2016-09-15 22:22
Some docs are still missing but we'll get them updated soon.

**Closed by npomfret** 2016-09-15 22:22 UTC

**Comment by abeikverdi** [comment] 2016-09-19 03:44
It works perfectly. Thanks for the quick update.
Cheers!
