### ISSUE TITLE
Android react-native-push-notification:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by tanodev85** [zo0r/react-native-push-notification#1985] opened 2021-05-12 09:28 UTC
Hi everyone,

since this morning the library has decided not to compile anymore while in recent days it worked fine I have version 7.2.1

this is the log:

> Task :react-native-push-notification:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
143 actionable tasks: 4 executed, 139 up-to-date
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:39: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:40: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:143: error: cannot find symbol
              .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                                            ^
  symbol:   class InstanceIdResult
  location: class RNPushNotification
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:145: error: cannot find symbol
                  public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                                       ^
  symbol: class InstanceIdResult
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:142: error: cannot find symbol
      FirebaseInstanceId.getInstance().getInstanceId()
      ^
  symbol:   variable FirebaseInstanceId
  location: class RNPushNotification
C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:289: error: cannot find symbol
                  FirebaseInstanceId.getInstance().deleteInstanceId();
                  ^
  symbol: variable FirebaseInstanceId
Note: C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\gaetano.amato\StudioProjects\smartinventory\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

I don't know what happened please help me

**Comment by kofoednielsen** [comment] 2021-05-12 09:30
I'm getting the exact same error, worked yesterday.

**Comment by dayaki** [comment] 2021-05-12 09:36
What could be wrong? worked perfectly yesterday but I started getting same error this morning.

**Comment by frapontillo** [comment] 2021-05-12 09:36
Duplicate of #1979.

**Comment by vlsimctco** [comment] 2021-05-12 09:36
Duplicate of https://github.com/zo0r/react-native-push-notification/issues/1979

**Comment by tanodev85** [comment] 2021-05-12 09:39
yes i'm sorry but is a duplicate of #1979 however try to add implementation com.google.firebase:firebase-messaging:21.1.0 to app/build.gradle and
firebaseMessagingVersion=21.1.0 to gradle.properties. Worked for me

**Closed** 2021-05-12 09:41 UTC
