### ISSUE TITLE
react-native-push-notification  Appears to be a git repo or submodule. 

### ISSUE THREAD

**Issue by behnamshateri** [zo0r/react-native-push-notification#1057] opened 2019-04-26 17:44 UTC
i have install react-native-push-notification and react-native link react-native-push-notification
but when i want to install another package or run npm install i face with this error

```
node_modules\react-native-push-notification: Appears to be a git repo or submodule.
```

**Comment by WhippetsAintDogs** [comment] 2019-04-26 20:54
Same here, I need to delete the package from my node_modules folder on the preinstall hook in order to make npm install work

**Comment by danielsotopino** [comment] 2019-04-28 21:14
Deleting the .git folder on react-native-push-notification and npm install afterwards makes it work.

**Comment by tmaly1980** [comment] 2019-04-30 13:02
Yes, but why does this happen in the first place?

**Comment by jeveloper** [comment] 2019-05-03 19:31
This is something new with npm 6.9 i think

**Comment by shreyasb07** [comment] 2019-05-03 22:41
remove any .git files present in the node_modules folder

In your terminal, from your project folder:
rm -rf node_modules/*/.git

**Comment by infiniteline** [comment] 2019-05-17 18:43
Yeah. This was definitely bothering me as well. I agree that it seems like it shouldn't be happening in the first place?

**Comment by mcrowe** [comment] 2019-05-17 20:54
@zo0r This is a bug in this package. The ".git" directly _should not_ be included in the npm package.

**Comment by jdegger** [comment] 2019-05-21 13:41
@zo0r is this going to be fixed anytime soon? I'm getting tired of not being able to do `npm install` with ease

**Comment by danielsotopino** [comment] 2019-05-21 17:58
I believe this is a problem with NPM (https://github.com/npm/npm/issues/20213)

**Comment by mlazari** [comment] 2019-05-22 09:53
This only happens in latest version, `3.1.3`. As a temporary workaround we use `3.1.2` for now, which seems to not have this problem.

**Comment by davidcorbin** [comment] 2019-06-03 11:55
Would love to see a fix for this! @zo0r Please update the npm package 😆

**Comment by jdegger** [comment] 2019-06-03 13:40
As a temporary fix we added the following to our `scripts` section of `package.json`:

```
    "preinstall": "rm -Rf ./node_modules/react-native-push-notification;"
```

This will probably not work on Windows but an similar solution on Windows can be applied.

**Comment by ft-worker** [comment] 2019-06-04 10:18
@mlazari i have the same issue with 3.1.2 version

**Comment by SergeyIsakhanyan** [comment] 2019-06-04 10:21
@mlazari I have the same problem with `3.1.2` version

**Comment by mlazari** [comment] 2019-06-04 10:32
@SergeyIsakhanyan Did you remove node_modules folder before downgrading to `3.1.2`?

**Comment by isaiahols** [comment] 2019-06-12 20:26
The issue is that .git was not ignored by putting it in your .npmignore.
I've made a PR to fix this! @zo0r Please merge

#1085

**Comment by mlazari** [comment] 2019-06-13 07:01
@isaiahols I'm looking at other dependencies we use that don't have this issue and they also don't have `.git` in their `.npmignore` files:
- https://github.com/apollographql/react-apollo/blob/master/.npmignore
- https://github.com/bamlab/react-native-formik/blob/master/.npmignore
- https://github.com/react-native-community/react-native-svg/blob/master/.npmignore

[react-native](https://github.com/facebook/react-native) doesn't even seem to have a `.npmignore` file as far as I can tell.

That could solve the issue, but it's probably not the only issue. `3.1.3` was probably published with a problematic `npm` version that has [the issue pointed above](https://github.com/npm/npm/issues/20213).

**Comment by isaiahols** [comment] 2019-06-13 13:53
@mlazari you are absolutely correct this is an not issue. The issue is that the npmignore is supposed to include the . git by default but it is not. So the current working solution while that is being sorted is to just include it manually. Then when the fix is up there is still no issue with including it in your npmignore as it is there by default. 

Just something to help in the meantime as this only seems to effect a few dependencies, this one included.

**Comment by tberghuis** [comment] 2019-06-16 05:33
Is there a valid reason for having a .git folder in the node_modules dir?

**Comment by drash-course** [comment] 2019-06-26 14:33
> Is there a valid reason for having a .git folder in the node_modules dir?

No. You should never have anything under version control down there because changes you make will never be saved between installs.

**Comment by Jackdouglas99** [comment] 2019-07-05 00:20
This PR will fix this issue. [https://github.com/zo0r/react-native-push-notification/pull/1085](#1085 )

**Closed** 2019-07-07 16:35 UTC

**Comment by nileshpandey3** [comment] 2019-09-01 05:27
> remove any .git files present in the node_modules folder
> 
> In your terminal, from your project folder:
> rm -rf node_modules/*/.git

This helped me.Thanks

**Comment by Rotemy** [comment] 2019-09-12 06:06
> rm -rf node_modules/*/.git

Worked!

**Comment by cihanbas** [comment] 2019-10-08 09:44
@SergeyIsakhanyan so thank you it worked

**Comment by schumannd** [comment] 2019-11-18 14:11
Any update on this? Still happening half a year later.
