### ISSUE TITLE
i am getting this issue while running

### ISSUE THREAD

**Issue by lalit-tsa** [zo0r/react-native-push-notification#1990] opened 2021-05-12 11:42 UTC
![image](https://user-images.githubusercontent.com/79075943/117969539-292f1980-b345-11eb-957c-ee08d642d7f1.png)

**Comment by Dallas62** [comment] 2021-05-12 11:50
Please search in issues before opening,
Duplicate of #1979

**Closed** 2021-05-12 11:49 UTC
