### ISSUE TITLE
Android: 'onNotification' not executing when app is closed and clicked to notification

### ISSUE THREAD

**Issue by rkostrab** [zo0r/react-native-push-notification#72] opened 2016-05-16 23:16 UTC
[android] 
Hello, when I put app in the background and I get push notification then `onNotification` is executed as I expect. But when I close app (using android back button) and I get push notification then `onNotification` is not executed.

I know `onNotification` is fired from Java in `onNewIntent` method. But I really need to pass some data from notification into JavaScript when application was closed before and I click on notification.

How to do it?

**Comment by j0hn** [comment] 2016-05-19 01:05
I'm having this same issue. I'm using [node-gcm](https://github.com/ToothlessGear/node-gcm) to send the notification to the app.

**Comment by eduardb** [comment] 2016-05-24 14:27
Same here. Some help on how to overcome this issue would be great.

**Comment by eduardb** [comment] 2016-05-25 15:23
UPDATE: It seems that onNotification is called after all when opening the app from the notification, but for some reason the YellowBox was not appearing when calling `console.warn()`. `Alert.alert()` does the trick though.

**Comment by j0hn** [comment] 2016-05-25 15:40
@eduardb even when your application is completely closed?

**Comment by eduardb** [comment] 2016-05-25 16:30
Completely, as in swiped away from the recents screen, yes.

**Comment by j0hn** [comment] 2016-05-25 17:51
Awesome, i couldn't achieve that. Would you be so kind to share some
example on how to make it work?

**Comment by eduardb** [comment] 2016-05-25 18:57
Have a look over this PR: https://github.com/novoda/spikes/pull/57

**Comment by florindobre** [comment] 2016-06-02 11:25
@eduardb how exactly do you have the Alert firing? I have an alert on the first line in onNotification, and it's working fine when the app is closed for iOS, but for Android it's not triggering.

**Comment by florindobre** [comment] 2016-06-06 13:05
After some debugging it looks like the `onMessageReceived` method from the `RNPushNotificationListenerService` class gets called when receiving the notification while the app is closed/in the background. But clicking on the notification itself only launches the app and does not pass its data to React.

@zo0r : any ideas on this? iOS working fine with clicking on notifications.

**Comment by rskull** [comment] 2016-06-08 13:07
if revert this commit, It work?

https://github.com/zo0r/react-native-push-notification/commit/1aa5c9684d8481428860d866ec50dea968cb19b8

**Comment by npomfret** [comment] 2016-06-08 22:18
I don't know if its related but I never get `onNotification`, weather the app is in the foreground or background.

https://github.com/zo0r/react-native-push-notification/issues/93

**Comment by rskull** [comment] 2016-06-09 04:25
@npomfret https://github.com/rskull/react-native-push-notification
I was solved with this repository.

**Comment by florindobre** [comment] 2016-06-09 08:41
Sending a notification with only the "data" field set (remove the "notification" field) works. Clicking on a notification triggers `onNotification ` once the app opens. It also gets triggered if the app is in the foreground.

**Comment by kfiroo** [comment] 2016-07-11 17:05
Hey all,
I think I'm having a similar issue,

When the app is closed (swiped from recent on android and swiped up in iOS) and I receive a notification, it is displayed properly by the OS but when I click it the `popInitialNotification` callback returns wrong data.

In iOS I receive:
`{foreground:false}`

In Android I receive:
`null`

Other then that everything seems to work perfectly!

Any idea what is going on?

Thanks,
kfir

**Comment by frangeris** [comment] 2016-07-20 06:18
I'm facing the same issue, the approach of @eduardb is not working for me, nothing is triggered when the app is entirely closed, I tried using the `Alert`, but nothing call `onNotification` method.

@florindobre Could you please provide a simple example snippet of you test?

> Sending a notification with only the "data" field set (remove the "notification" field) works

**Comment by kfiroo** [comment] 2016-07-20 08:55
@frangeris This pull request was supposed to resolve this issue [137](https://github.com/zo0r/react-native-push-notification/pull/137)

Not sure @zo0r published a new version yet but you can checkout this version and see if that works for you

**Comment by frangeris** [comment] 2016-07-20 15:42
@kfiroo Thanks for the info.

Not sure if I'm correct, Am I missing something?

```javascript
module.exports = React.createClass({
    componentWillMount() {
        PushNotification.configure({
            popInitialNotification: (notification) => {
                // when app is entirely closed and click on push notification
                console.log('received', notification)
            },
            onNotification: (notification) => {
                // ...
            }
        })
        // ...
    }
})
```

**Comment by kfiroo** [comment] 2016-07-20 16:03
@frangeris Looks like you might have misread the [docs](https://github.com/zo0r/react-native-push-notification#usage)

When calling `PushNotification.configure` the `popInitialNotification` field is a boolean flag indicating whether to pop the initial notification or not, if true, it will try to pop the notification then normalize it and call the `onNotification` function you passed to the `configure`.

Hope that makes sense to you :)

**Comment by frangeris** [comment] 2016-07-20 16:15
@kfiroo Thanks for the aclaration, about the value of the property as function instead of boolean, I was just testing a different approach, because neither of both is working for me, but ok using true (default) still not working.

Thanks

**Comment by kfiroo** [comment] 2016-07-20 16:21
@frangeris I think we need more information to be able to help you, like:
* Android / iOS? 
* Are you using the latest code for this library?
* Is the app closed or in the background?
* Do you receive the notification in your phone at all?

**Comment by frangeris** [comment] 2016-07-20 16:24
* Android 4.2.2
* `2.0.1`
* Closed
* Yep, everything is working fine, except when app is entirely closed

Thanks

**Comment by zo0r** [comment] 2016-07-20 16:27
@frangeris @kfiroo when the app is entirely closed (Android) the callback `onNotification` is never called, its how `RN` works (the bridge java->node->react is dead at this point), the `onNotification` will be called when the user tap the notification again.

**Comment by amrdraz** [comment] 2016-07-20 16:29
@zo0r then how do we trigger the notification message when the app is closed, or is this not possible?

**Comment by frangeris** [comment] 2016-07-20 16:35
Thanks @zo0r, valuable information! 

What would you suggest for approach this?

**Comment by zo0r** [comment] 2016-07-20 16:39
@frangeris @amrdraz its not possible for now **(2.0.1)**, I think a way to capture and execute the callback is re-open the activity in background (open and `moveTaskToBack`?) (if dead) and then execute `onNotification` again.

As its not an user-intended behavior, (I think) sending the `'forcesReactNativeDelivery': bool` prop in the push data to re-open (if dead) the activity and execute the `onNotification` callback.

Note that **forcesReactNativeDelivery** thing is not implemented yet, just a suggestion.

**Comment by kfiroo** [comment] 2016-07-20 16:53
@zo0r @amrdraz @frangeris Actually my PR made it possible, I'm using it in my app on production.

If I understand it correctly, this is the case in every Android app, the app is closed so you cannot handle the initial notification right away.  
This is why the notification data is stored on an `Intent` that is available on the `Activity`.  

In [RNPushNotificationHelper.java#L213](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L213) we create a `PendingIntent` that wraps the notification `Intent` and later when the app starts and the JS code calls `popInitialNotification` this code in 
[RNPushNotification.getInitialNotification](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java#L148) we get the current `Activity` from it we get the `Intent` which holds the `notification` data which we return to the client.

What do you think?

**Comment by zo0r** [comment] 2016-07-20 17:00
@kfiroo you're right, but as I understand what @frangeris want is the`onNotification` trigger immediately after the notification is received even if the app is closed.

**Comment by frangeris** [comment] 2016-07-20 17:06
Not exactly that case, this is the perfect scenario:

1. App is entirely closed
2. Push notification on phone
3. User click on that notification
4. Receive that data in `onNotification`

If I could get `onNotification` when user click on notification when the app is closed, that will be fine...

That's what I can't get @kfiroo, could you provide an example snippet please?

**Comment by kfiroo** [comment] 2016-07-20 17:14
@frangeris When I think about it I had some trouble finding the right structure of the notification I send from my server, that might be your problem!

my GCM payload looks like this: 
```javascript
JSON.stringify({
    data: {
        message: 'some message text',
        sound: 'default',
        // custom data goes here
        data: JSON.stringify({
            key: 'value'
        })
    }
})
```

**Comment by amrdraz** [comment] 2016-07-20 17:28
@kfiroo I confirm that when I sent myself a push notification with the correct format it worked

**Comment by frangeris** [comment] 2016-07-20 17:43
@amrdraz I'm using Firebase Cloud Messaging, so checking docs...

Thanks @kfiroo

**Comment by kfiroo** [comment] 2016-07-20 17:45
@amrdraz Great to hear that!  
We could probably tweak the code to be less strict regarding the remote notification format, but I'm not an Android or iOS developer so I can't say if there is a standard that we should conform to.

Currently, as I can see from the code, the only restrictions are that the top level object will have a `data` field and that inside this `data` object we need a `message` fields and it has to be a string.

Here we look for the data field on the root object - [RNPushNotificationListenerService.java#L18](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L18) - not sure it's mandatory.
Here we simply return if we have no `message` field - [RNPushNotificationHelper.java#L92](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L92)

**Comment by frangeris** [comment] 2016-07-20 19:23
Hey @kfiroo @amrdraz I've no idea why now is working :|

This is what I did, I was using firebase endpoint (not working), then I changed to test using the code of @amrdraz (using GCM endpoint), start working, rollback and test again with firebase endpoint, works... :/

Is possible that switching between endpoint could fix something behind scenes?

Another note is that `data` nested inside `data` is not required, the next request works on both (GCM, FCM):

```bash
curl -X POST -H "Authorization: key=<MY_KEY>" -H "Content-Type: application/json" -d '
{
  "data": {
      "title": "Hello there",
      "message": "some message text",
  },
  "to" : "<DEVICE_TOKEN>"
}' 'https://fcm.googleapis.com/fcm/send'
```

And from React native:

```javascript
module.exports = React.createClass({
    componentWillMount() {
        PushNotification.configure({
            // popInitialNotification: true,
            onNotification: (notification) => {
                console.log(notification)
            }
        })
    }
})
```

Thank's guys for the help!

**Comment by kfiroo** [comment] 2016-07-20 21:34
@frangeris Great to hear :)
Good luck

**Comment by kfiroo** [comment] 2016-07-20 21:35
@zo0r  I think we can close this

**Comment by frangeris** [comment] 2016-07-20 21:35
Yep, go ahead...

**Closed** 2016-07-20 21:35 UTC

**Comment by didil** [comment] 2017-04-25 16:08
shouldnt some of this be in the documentation ? it ended up working for me but its fairly non trivial to understand that you need a specific message format to get a notification displayed and clicked outside the app to trigger onNotification

**Comment by lucask42** [comment] 2017-09-05 21:57
If you are overriding onNewIntent in `MainActivity.java` and you do not call super on onNewIntent then that may be preventing onNotification from firing.

This could happen if you were to, say, use react-native-branch-deep-linking and follow their setup instructions.  You would override onNewIntent like this
```java
    @Override
    public void onNewIntent(Intent intent) {
        setIntent(intent);
    }
```

A possible fix to get onNotification to fire is to add super.onNewIntent(intent):
```java
    @Override
    public void onNewIntent(Intent intent) {
        setIntent(intent);
        super.onNewIntent(intent)
    }
```
